
extends Node
var namefile = load("res://files/scripts/characters/names.gd").new()
var names = namefile.names


var races = {
	Human = {
		skin = ['pale', 'fair', 'olive', 'tan'],
		eyecolor = ['blue', 'green', 'brown', 'hazel', 'black', 'gray'],
		haircolor = ['blond', 'red', 'auburn', 'brown', 'black'],
		surname = names.humansurname,
		description = "Humans are a highly successful militaristic people whose members can be found throughout much of the world, their presence often receiving a mixed reception. Slavery is a common part of human society, viewed as a civilized form of alternative punishment, with many laws and businesses based around the concept. Because of this slave driven culture, you have found that humans tend to be the most widely accessible residents, servants, and slaves.",
		details = "[color=aqua]Racial trait: +50% Fear and Obedience during meet interactions.[/color]\n\n[color=yellow]Stat potential: Strength - {str_max}, Agility - {agi_max}, Magic - {maf_max}, Endurance - {end_max} [/color]",
		breedingnotes = "In addition to the many successful human hybrid races created in the past, humans are the best known substrate for the creation of new races through transformative magic. Of course, most mages lack the requisite skill not to mention access to an interdimensional transformative matrix, both of which are needed to create new races in this way, but there are still similar feats that may be accomplished through selective breeding, an often convivial pursuit and as relatively simple as putting the proverbial round peg in the correct hole.",
		racialstatbonuses = "Strength+, Agility+, Magic+, Endurance+",
		purebloodbonus = "Strength+, Agility+, Magic+, Endurance+",
		otherracialcharacteristics = "None",
		elementalmod = {
			fire = 0,
			wind = 0,
			water = 0,
			earth = 0,
			nature = 25,
			corruption = 0,
		},
		elementalbonuses = "Fire (Strength+), Wind (Agility+), Water (Magic+), Earth (Endurance+)",
		naturebonus = "None",
		highcorruptionbonus = "No effect",
		lowcorruptionbonus = "No effect",
		breedingquirk = "Combining with few races reduces attributes, but combining with a large number of races increases attributes exponentially.",
		mutations = "None",
		pricemod = 1,
		#ralph5
		marketup = ["Demand for [color=aqua]humans[/color] rises inexplicably.\n"],
		marketdown = ["It seems [color=aqua]humans[/color] aren't being purchased very quickly. Prices fall.\n"],
		single = "human",
		plural = "humans",
		singlepos = "human's",
		pluralpos = "humans'",
		#/ralph5
		startingrace = true,
		wimbornrace = true,
		gornrace = true,
		frostfordrace = true,
		banditrace = true,
		uncivilized = false,
		sebastian = false,
		shade = {male = "res://files/buttons/inventory/shades/Human_M.png", female = "res://files/buttons/inventory/shades/Human_F.png"},
		stats = {
			str_max = 5, 
			agi_max = 2, 
			maf_max = 3, 
			end_max = 4
		}
	},
	Elf = {
		surname = names.elfsurname,
		ears = ['pointy'],
		haircolor = ['white', 'green', 'purple', 'blue', 'blond', 'red', 'auburn'],
		description = "Elves are famous among the various races for the legends and stories of ancient times, when elves held a similar status to modern humans. These tales speak of elves as arrogant, and in command of powerful nature magic, but ultimately spelling their own downfall in some great act of folly.\n\nModern elves bear few connections to their ancestors beyond physical appearance and a close connection to nature. In stark contrast, their lives are often fairly humble and reclusive, generally staying deep within forests. There is no evidence to suggest any inherent magic found in modern elves, but this hardly impedes their popularity.",
		details = "[color=aqua]Racial trait: Improves obedience when allowed to lead during sex sequence.[/color]\n\n[color=yellow]Stat potential: Strength - {str_max}, Agility - {agi_max}, Magic - {maf_max}, Endurance - {end_max} [/color]",
		breedingnotes = "There are multiple opportunities to breed superior Elf hybrids. Elves in general owe some of their amazing finesse and grace of movement to their fine bone structure in addition to a simple advantage of reflex and though cut off from destructive magic, elves still gain some benefit from any secondary ancestry attuned to elemental forces.",
		racialstatbonuses = "Agility++",
		purebloodbonus = "Magic+",
		otherracialcharacteristics = "Beauty+, Fertility-, Charm+",
		elementalmod = {
			fire = 0,
			wind = 25,
			water = 0,
			earth = 0,
			nature = 50,
			corruption = 25,
		},
		elementalbonuses = "Wind (Magic+)",
		naturebonus = "Agility+",
		highcorruptionbonus = "Strength+, Agility-",
		lowcorruptionbonus = "Agility+",
		breedingquirk = "Gains minor stat bonuses from all elements.",
		mutations = "Huldrekall, Nymph, Siren",
		pricemod = 1.5,
		#ralph5
		marketup = ["Demand for [color=aqua]elves[/color] is up.\n"],
		marketdown = ["[color=aqua]Elves[/color] just aren't in demand lately. Prices fall.\n"],
		single = " elf",
		plural = " elves",
		singlepos = " elf's",
		pluralpos = " elves'",
		#/ralph5
		startingrace = true,
		wimbornrace = true,
		gornrace = false,
		frostfordrace = true,
		banditrace = true,
		uncivilized = false,
		sebastian = false,
		shade = {male = "res://files/buttons/inventory/shades/Elf_M.png", female = "res://files/buttons/inventory/shades/Elf_F.png"},
		stats = {	
			str_max = 3,	
			agi_max = 5,	
			maf_max = 4,	
			end_max = 3,	
		},	
	},
	'Tribal Elf' : {
		surname = names.elfsurname,
		description = "Elves are famous among the various races for the legends and stories of ancient times, when elves held a similar status to modern humans. These tales speak of elves as arrogant, and in command of powerful nature magic, but ultimately spelling their own downfall in some great act of folly.\n\nTribal elves belong to less known tribes, rumored to be separated from main groups and living in warmer regions.",
		details = "[color=aqua]Racial trait: Temporal effects from potions and spells last longer.[/color]\n\n[color=yellow]Stat potential: Strength - {str_max}, Agility - {agi_max}, Magic - {maf_max}, Endurance - {end_max} [/color]",
		breedingnotes = "Elves in general owe some of their amazing finesse and grace of movement to their fine bone structure in addition to a simple advantage of reflex. Compared to other elves, tribal elves make for mediocre spell casters, but are often physically more formidable.",
		racialstatbonuses = "Agility++",
		purebloodbonus = "Endurance+",
		otherracialcharacteristics = "Beauty+, Fertility-, Confidence++",
		elementalmod = {
			fire = 25,
			wind = 0,
			water = 0,
			earth = 0,
			nature = 75,
			corruption = 25,
		},
		elementalbonuses = "Fire (Strength+)",
		naturebonus = "Agility+",
		highcorruptionbonus = "Magic+, Strength-",
		lowcorruptionbonus = "Magic-, Strength+",
		breedingquirk = "Gains minor stat bonuses from all elements.",
		mutations = "Huldrekall, Nymph, Ifrit",
		pricemod = 1.5,
		#ralph5
		marketup = ["Demand for [color=aqua]tribal elves[/color] is up.\n","The capitol is going through a serious phase of forest fever. Demand for [color=aqua]tribal elves[/color] is up.\n"],
		marketdown = ["[color=aqua]Tribal elves[/color] just aren't in as much demand lately. Prices fall.\n"],
		single = " elf",
		plural = " elves",
		singlepos = " elf's",
		pluralpos = " elves'",
		#/ralph5
		startingrace = true,
		wimbornrace = true,
		gornrace = false,
		frostfordrace = false,
		banditrace = true,
		uncivilized = false,
		sebastian = true,
		ears = ['pointy'],
		skin = ['tan', 'brown', 'dark'],
		eyecolor = ['blue', 'green', 'amber', 'red', 'purple'],
		haircolor = ['white', 'green', 'purple', 'blue', 'blond', 'red', 'auburn'],
		shade = {male = "res://files/buttons/inventory/shades/Elf_M.png", female = "res://files/buttons/inventory/shades/Elf_F.png"},
		stats = {	
			str_max = 4,	
			agi_max = 5,	
			maf_max = 3,	
			end_max = 4,	
		},
	},
	'Dark Elf' : {
		surname = names.elfsurname,
		description = "Dark Elves are a race, considered a branching species of elf. Little is known about their history and motherland, if they ever had one at all, as their underground cities are spread thin across multiple continents, and are even more difficult to enter than to locate.\n\nBeyond a preference for isolation and their general appearance, Dark Elves are quite different from their cousins in both attitude and culture. However, what sets them apart most is the unusual pigmentation of their skin; a dark colors with occasional blue tint. The unusual pigmentation is the subject of much debate and speculation, with theories ranging from natural mutation, to the byproduct of ancient beings.",
		details = "[color=aqua]Racial trait: sexual actions give 20% more mana.[/color]\n\n[color=yellow]Stat potential: Strength - {str_max}, Agility - {agi_max}, Magic - {maf_max}, Endurance - {end_max} [/color]",
		breedingnotes = "Elves in general owe some of their amazing finesse and grace of movement to their fine bone structure in addition to a simple advantage of reflex. As a consequence of their original purpose, in most lands they are thought to be infertile outside their race and in addition to their enhanced affinity for all elements Dark Elves are known to be particularly sensitive to mana corruption. This presents a potential double-edged sword in that offspring resulting from unions with corrupted bloodlines often suffer distinct shortcomings.",
		racialstatbonuses = "Agility+, Magic+",
		purebloodbonus = "Strength+",
		otherracialcharacteristics = "Beauty+, Fertility-, Wit+",
		elementalmod = {
			fire = 0,
			wind = 0,
			water = 25,
			earth = 0,
			nature = 50,
			corruption = 50,
		},
		elementalbonuses = "Fire(Str+), Wind(Agi+), Water(Mag+), Earth(End+)",
		naturebonus = "Amplifies Elemental Bonuses",
		highcorruptionbonus = "All stats-, Beauty-, Fertility-, Charm-",
		lowcorruptionbonus = "All stats+ based on elemental make-up, Charm+",
		breedingquirk = "Gains stat bonuses from all elements.",
		mutations = "Huldrekall, Nymph, Undine",
		pricemod = 2.5,
		#ralph5
		marketup = ["Demand for [color=aqua]dark elves[/color] is up.\n","[color=aqua]Dark Elves[/color] are the latest status symbols for up and coming mages. Slavers simply cannot keep up with demand.\n","A consortium of mages is attempting to create a new species and [color=aqua]dark elves[/color] are in higher demand for their mana output.\n"],
		marketdown = ["[color=aqua]Dark Elves[/color] just aren't selling for what they used to.\n","Rumors abound that sex with subterranean species promotes the cockrot. Demand for [color=aqua]dark elves[/color] falls.\n"],
		single = " elf",
		plural = " elves",
		singlepos = " elf's",
		pluralpos = " elves'",
		#/ralph5
		startingrace = false,
		wimbornrace = false,
		gornrace = false,
		frostfordrace = false,
		banditrace = false,
		uncivilized = false,
		sebastian = true,
		ears = ['pointy'],
		skin = ['blue', 'purple', 'pale blue'],
		haircolor = ['white', 'green', 'purple', 'blue', 'blond', 'red', 'auburn'],
		shade = {male = "res://files/buttons/inventory/shades/Elf_M.png", female = "res://files/buttons/inventory/shades/Elf_F.png"},
		stats = {	
			str_max = 4,	
			agi_max = 5,	
			maf_max = 6,	
			end_max = 3,	
		},
	},
	Orc = {
		surname = names.orcsurname,
		description = "Orcs are among the most recognizable races for their unique green skin color, and naturally untamed appearances. Orcs are widely considered barbarians for their tribal nature, but those who study them have found a diverse and highly communal society, far more civilized than it may first appear.\n\nOrcs reside primarily in the south, within the borders of Gorn; a powerful nation. It is well documented in local history and folklore that as the scale and ferocity of the tribal wars grew, foreign invaders were pushed further out, allowing Gorn’s relatively undisturbed development. These days, though the constant wars have ended, the remaining tribes receive regular offerings to stay within the nation’s borders as a deterrent and to maintain friendly relations.",
		details = "[color=aqua]Racial trait: wounds heal quicker.[/color]\n\n[color=yellow]Stat potential: Strength - {str_max}, Agility - {agi_max}, Magic - {maf_max}, Endurance - {end_max} [/color]",
		breedingnotes = "Orcs hybrids are a lucrative side business for many breeders in the local chapter of the mage guild as in most of the rest of the world they appear to be infertile outside their race.  By reputation, pure blood's are preferred by many a warlord and make stolid infantrymen, but orc females are often unattractive. It is a well known phenomenon for orcish warbands to raid villages with little other motivation than to carry off attractive females of other species to mate with. The local guild's secret to avid intraspecies copulation is to throw just a little elf into the mix.",
		racialstatbonuses = "Strength+, Endurance+",
		purebloodbonus = "Endurance+",
		otherracialcharacteristics = "Beauty-, Courage+, Height+",
		elementalmod = {
			fire = 25,
			wind = 0,
			water = 0,
			earth = 0,
			nature = 25,
			corruption = 75,
		},
		elementalbonuses = "Fire (Strength+)",
		naturebonus = "Endurance+",
		highcorruptionbonus = "Strength+, Agility-, Beauty-",
		lowcorruptionbonus = "Strength-, Agility+, Beauty+",
		breedingquirk = "Elvish blood results in more attractive offspring.",
		mutations = "Gnoll, Lizardman, Troll",
		pricemod = 1.5,
		#ralph5
		marketup = ["Demand for [color=aqua]orcs[/color] is up.\n","A nearby warlord is looking to replenish his infantry. Pricing for [color=aqua]orcs[/color] is up.\n"],
		marketdown = ["An unexpected truce between warring factions has put a damper on trade in [color=aqua]orcs[/color]. Prices fall.\n"],
		single = " orc",
		plural = " orcs",
		singlepos = " orc's",
		pluralpos = " orcs'",
		#/ralph5
		startingrace = true,
		wimbornrace = false,
		gornrace = true,
		frostfordrace = false,
		banditrace = true,
		uncivilized = false,
		sebastian = false,
		shade = {male = "res://files/buttons/inventory/shades/Orc_-M.png", female = "res://files/buttons/inventory/shades/Orc_F.png"},
		skin = ['green'],
		ears = ['pointy'],
		stats = {	
			str_max = 6,	
			agi_max = 3,	
			maf_max = 1,	
			end_max = 5,	
		},
	},
	Gnome = {
		bodyshape = ['shortstack'],
		description = "Though nowadays the gnome capital is open as a tourist spot, there are stories and documents stating that generations ago, they were once humans sealed within the city by demons, experimented on and mutated into the forms they have today.\n\nThough they are a stocky, physically weak race, they compensate for their shortcomings with outstanding intellect, holding a commanding lead as the world’s frontrunners in technology.",
		details = "[color=aqua]Racial trait: studying at Library twice as effective. [/color]\n\n[color=yellow]Stat potential: Strength - {str_max}, Agility - {agi_max}, Magic - {maf_max}, Endurance - {end_max} [/color]",
		breedingnotes = "Gnomes are often overlooked, but not in guild circles. They make stellar clerks and excellent lab assistants for those who can put up with the little know-it-alls...\n*ahem*\nGnomes exhibit a strong affinity for nature, but breeding with demons can also occaisionally yield interesting results.",
		racialstatbonuses = "Endurance++",
		purebloodbonus = "Agility+",
		otherracialcharacteristics = "Wit+, Height---",
		elementalmod = {
			fire = 0,
			wind = 0,
			water = 0,
			earth = 100,
			nature = 25,
			corruption = 100,
		},
		elementalbonuses = "Earth (Magic+)",
		naturebonus = "Magic++",
		highcorruptionbonus = "N/A",
		lowcorruptionbonus = "Endurance-, Agility+",
		breedingquirk = "Agility+ with Bunny/Harpy ancestry, Endurance- with Harpy ancestry.",
		mutations = "Imp, Mousekin",
		pricemod = 1.5,
		#ralph5
		marketup = ["Demand for [color=aqua]gnomes[/color] is up.\n","Goblins revolt at a nearby mine and they are left shorthanded. The taskmasters are looking for an alternative species of slaves and have begun offering a premium for [color=aqua]gnomes[/color].\n"],
		marketdown = ["Pricing for [color=aqua]gnomes[/color] falls. Employers and slaveholders alike must have had enough of the little know-it-alls.\n"],
		single = " gnome",
		plural = " gnomes",
		singlepos = " gnome's",
		pluralpos = " gnomes'",
		#/ralph5
		startingrace = false,
		wimbornrace = false,
		gornrace = true,
		frostfordrace = false,
		banditrace = false,
		uncivilized = false,
		sebastian = true,
		shade = {male = "res://files/buttons/inventory/shades/Gnome_M.png", female = "res://files/buttons/inventory/shades/Gnome_F.png"},
		height = ['tiny'],
		stats = {	
			str_max = 3,	
			agi_max = 3,	
			maf_max = 5,	
			end_max = 3,	
		},
	},
	Goblin = {
		bodyshape = ['shortstack'],
		description = "Goblins are a race of cave dwellers, loosely resembling short, green-skinned elves. They have existed for a very long time, but despite their prevalence rarely played any influential role. While often been considered nothing more than common monsters, they have surprising skill and understanding, putting them on par with many humanoid races in term of sentience.",
		details = "[color=aqua]Racial trait: pregnancy progresses lot quicker. [/color]\n\n[color=yellow]Stat potential: Strength - {str_max}, Agility - {agi_max}, Magic - {maf_max}, Endurance - {end_max} [/color]",
		breedingnotes = "Goblins are frequently underestimated, often to the mortal peril of their detractors. Additionally, goblin blood is often mutanagenic and their offspring in certain combinations barely resemble the parents. For example, it's rumored that long ago goblins were made to breed with orcs to quickly produce armies of hobgoblins, powerful from birth but much like mules in that they were seldom capable of siring offspring of their own.",
		racialstatbonuses = "Strength+, Agility+",
		purebloodbonus = "Magic+",
		otherracialcharacteristics = "Lewdness+, Pliability++, Beauty--, Height---",
		elementalmod = {
			fire = 0,
			wind = 0,
			water = 0,
			earth = 75,
			nature = 100,
			corruption = 100,
		},
		elementalbonuses = "Earth (Strength+)",
		naturebonus = "Fertility+++",
		highcorruptionbonus = "N/A",
		lowcorruptionbonus = "Beauty+,  Agility+, Strength-",
		breedingquirk = "Extra penis size from Orc heritage.",
		mutations = "Kobold, Gremlin, Hobgoblin, Redcap",
		pricemod = 1.5,
		#ralph5
		marketup = ["Demand for [color=aqua]goblins[/color] is up inexplicably.\n","A nearby warlord is looking for sappers and cannon fodder for a siege. Pricing for [color=aqua]goblins[/color] is up.\n"],
		marketdown = ["[color=aqua]Goblins[/color] have become even less popular of late. Prices fall.\n","Rumors abound that sex with subterranean species promotes the cockrot. Demand for [color=aqua]goblins[/color] falls.\n","Prices for [color=aqua]goblins[/color] fall as rumors that slave brands fail to prevent violence against their masters circulate.\n"],
		single = " goblin",
		plural = " goblins",
		singlepos = " goblin's",
		pluralpos = " goblins'",
		#/ralph5
		startingrace = false,
		wimbornrace = false,
		gornrace = true,
		frostfordrace = false,
		banditrace = true,
		uncivilized = false,
		sebastian = true,
		shade = {male = "res://files/buttons/inventory/shades/Goblin_M.png", female = "res://files/buttons/inventory/shades/Goblin_F.png"},
		skin = ['green'],
		ears = ['pointy'],
		height = ['tiny'],
		stats = {	
			str_max = 3,	
			agi_max = 5,	
			maf_max = 3,	
			end_max = 3,	
		},
	},
	Fairy = {
		bodyshape = ['shortstack'],
		description = "Modern fairies, often referred to as city fairies by some parts of the magic community, are an unexpected evolution of nature spirits sharing the same name, resulting from interaction with outsiders and migration into cities. These fairies have retained much of the cute, friendly, and playful attitudes of the spirits they came from, making them popular for positions with high volumes of public interaction.",
		details = "[color=aqua]Racial trait: doubles the daily base stress dissipation.[/color]\n\n[color=yellow]Stat potential: Strength - {str_max}, Agility - {agi_max}, Magic - {maf_max}, Endurance - {end_max} [/color]",
		breedingnotes = "A properly trained Fairy can make a fine assistant, but as a race they are typically unsuited to combat being weak of arm and frail of constitution aside from their stature. These shortcomings can be mitigated to some degree however through crossbreeding with other winged races for enhanced aerodynamics or with hardier specimens of similar stature for enhanced endurance.",
		racialstatbonuses = "Magic++",
		purebloodbonus = "Agility+",
		otherracialcharacteristics = "Charm+, Pliability+, Height---, Lewdness+ (females)",
		elementalmod = {
			fire = 0,
			wind = 75,
			water = 0,
			earth = 0,
			nature = 75,
			corruption = 0,
		},
		elementalbonuses = "Wind (Agility+)",
		naturebonus = "Magic",
		highcorruptionbonus = "Strength+, Endurance+, Magic-",
		lowcorruptionbonus = "N/A",
		breedingquirk = "Agility+ from breeding with other winged races.",
		mutations = "Sylph",
		pricemod = 2,
		#ralph5
		marketup = ["Demand for [color=aqua]faeries[/color] is up.\n","Word is that an arena boss from across the sea has started an aerial league and has been buying up [color=aqua]faeries[/color].\n"],
		marketdown = ["Mages have been favoring hardier races and demand for [color=aqua]faeries[/color] is down. Prices fall.\n"],
		single = " fairy",
		plural = " fairies",
		singlepos = " fairy's",
		pluralpos = " fairies'",
		#/ralph5
		startingrace = false,
		wimbornrace = true,
		gornrace = false,
		frostfordrace = false,
		banditrace = false,
		uncivilized = true,
		sebastian = true,
		shade = {male = "res://files/buttons/inventory/shades/Fairy_M.png", female = "res://files/buttons/inventory/shades/Fairy_F.png"},
		eyecolor = ['blue', 'green', 'amber', 'red', 'purple'],
		haircolor = ['white', 'green', 'purple', 'blue', 'blond', 'red', 'auburn'],
		ears = ['pointy'],
		wings = ['insect'],
		height = ['tiny'],
		surname = '',
		stats = {	
			str_max = 2,	
			agi_max = 5,	
			maf_max = 6,	
			end_max = 2,	
		},
	},
	Seraph = {
		ears = ['pointy'],
		description = "Seraphs were named because of their similarity in appearance to angels, the winged servants of divinity spoken of in myth. The reclusiveness of seraphs has led to a lack of research, but common theories are that they are a subspecies of harpy, an artificial race created accidentally many generations ago, or the descendants of an alien race that migrated from somewhere within the outer planes.\n\nSimilar to demons, seraphs seem to exhibit many behavioral traits in line with their mythic counterparts, such as a prudish nature and a slight inclination towards public service, though it’s unknown if these traits are universal, or if they come down to an individual basis.",
		details = "[color=aqua]Racial trait: +4 speed in combat[/color]\n\n[color=yellow]Stat potential: Strength - {str_max}, Agility - {agi_max}, Magic - {maf_max}, Endurance - {end_max} [/color]",
		breedingnotes = "Specimens are still somewhat rare so results have not been corroberated, but one mage has noted that the minds of Seraph dominant hybrids are heavily influenced by the baser instincts of the races they are bred with. Additionally, he notes that Seraph suffer a sensitivity to mana corrupted blood similar to Dark Elves.",
		racialstatbonuses = "Magic++",
		purebloodbonus = "Strength+",
		otherracialcharacteristics = "Beauty++",
		elementalmod = {
			fire = 50,
			wind = 50,
			water = 0,
			earth = 0,
			nature = 25,
			corruption = 0,
		},
		elementalbonuses = "Fire (Strength+) Wind (Agility+)",
		naturebonus = "Magic+, Fertility&Mental stats++ depending on races",
		highcorruptionbonus = "Magic-, Fertility&Mental stats-- depending on races",
		lowcorruptionbonus = "N/A",
		breedingquirk = "Breeding with Demons is forbidden in Seraph societies.",
		mutations = "Nephilim",
		pricemod = 2.5,
		#ralph5
		marketup = ["Demand for [color=aqua]seraphs[/color] is up.\n","Word is that an arena boss from across the sea has started an aerial league and has been buying up [color=aqua]seraphs[/color].\n"],
		marketdown = ["Some lab-rat mage has been modifying humans and passing them off as [color=aqua]Seraphs[/color]. Prices fall as buyers become leary of being cheated.\n"],
		single = " seraph",
		plural = " seraphs",
		singlepos = " seraph's",
		pluralpos = " seraphs'",
		#/ralph5
		startingrace = true,
		wimbornrace = false,
		gornrace = false,
		frostfordrace = false,
		banditrace = false,
		uncivilized = false,
		sebastian = true,
		shade = {male = "res://files/buttons/inventory/shades/Seraph_M.png", female = "res://files/buttons/inventory/shades/Seraph_F.png"},
		wings = ['feathered_black', 'feathered_white', 'feathered_brown'],
		stats = {	
			str_max = 4,	
			agi_max = 5,	
			maf_max = 3,	
			end_max = 3,	
		},
	},
	Demon = {
		description = "Though they share a name and certain physical traits, modern demons bear mostly superficial resemblance to their ancient counterparts, who were driven into the great depths of the underground, and even into other dimensions. It is speculated that modern demons are either the offspring of humans and actual monsters, the byproduct of extensive magical corruption similar to gnomes, or as more recent research suggests the descendants of an entirely separate race that migrated from the outer planes.\n\nThough demons are often feared and reviled, those with outstanding talent or skill often receive recognition for their abilities, so it is not entirely uncommon to see demons among the elite, or in high profile positions.",
		details = "[color=aqua]Racial trait: laboratory modifications are cheaper.[/color]\n\n[color=yellow]Stat potential: Strength - {str_max}, Agility - {agi_max}, Magic - {maf_max}, Endurance - {end_max} [/color]",
		breedingnotes = "Similar to Goblins, demonic progeny are often subject to mutation. Though there is much debate as to the source, Demon mana is clearly tainted and when invested in Demon dominant hybrids often causes them to take on animalistic physical traits from the races that make up their secondary ancestry.",
		racialstatbonuses = "Strength+, Magic+",
		purebloodbonus = "Strength+",
		otherracialcharacteristics = "Charm++",
		elementalmod = {
			fire = 75,
			wind = 0,
			water = 0,
			earth = 0,
			nature = 25,
			corruption = 100,
		},
		elementalbonuses = "Fire (Agility+)",
		naturebonus = "Attributes++ depending on races bred with",
		highcorruptionbonus = "N/A",
		lowcorruptionbonus = "Attributes- depending on races bred with",
		breedingquirk = "Demons jokingly encourage their spawn to breed with Seraphs.",
		mutations = "Ogre, Succubus, Incubus, Rusalka",
		pricemod = 2.5,
		#ralph5
		marketup = ["Demand for [color=aqua]demons[/color] is up.\n","Word is that an arena boss from across the sea has started an aerial league and has been buying up [color=aqua]demons[/color].\n"],
		marketdown = ["Supply of [color=aqua]demons[/color] exceeds demand. Prices fall.\n","Prices for [color=aqua]demons[/color] fall as rumors that slave brands fail to prevent violence against their masters circulate.\n"],
		single = " demon",
		plural = " demon's",
		singlepos = " demon's",
		pluralpos = " demons'",
		#/ralph5
		startingrace = true,
		wimbornrace = true,
		gornrace = false,
		frostfordrace = false,
		banditrace = true,
		uncivilized = false,
		sebastian = true,
		shade = {male = "res://files/buttons/inventory/shades/Demon_M.png", female = "res://files/buttons/inventory/shades/Demon_F.png"},
		ears = ['pointy'],
		tail = ['demon'],
		wings = ['leather_black', 'leather_red'],
		horns = ['short', 'long_straight', 'curved'],
		stats = {	
			str_max = 5,	
			agi_max = 4,	
			maf_max = 4,	
			end_max = 3,	
		},
	},
	Dryad = {
		description = "Dryads are a virtual unknown, with little information on their natural habitat and reproduction. It is speculated that they are nature spirits born from old trees that have absorbed a large amount of mana.",
		details = "[color=aqua]Racial trait: forage is 40% more effective.[/color]\n\n[color=yellow]Stat potential: Strength - {str_max}, Agility - {agi_max}, Magic - {maf_max}, Endurance - {end_max} [/color]",
		breedingnotes = "These creatures have begun appearing in greater frequency in the forests between Wimborn and Frostford. These tree nymphs seem to be heavily infused with nature magic and their progeny often resonate with the blood of other races known for affinity with nature or certain elements. Mages are encouraged to capture these creatures for further study given any opportunity.",
		racialstatbonuses = "Magic+, Endurance+",
		purebloodbonus = "Magic+",
		otherracialcharacteristics = "None",
		elementalmod = {
			fire = 0,
			wind = 0,
			water = 25,
			earth = 25,
			nature = 100,
			corruption = 0,
		},
		elementalbonuses = "Water (Strength+), Earth (Magic+)",
		naturebonus = "Endurance",
		highcorruptionbonus = "Strength++, Endurance-, Magic-",
		lowcorruptionbonus = "N/A",
		breedingquirk = "Fire required to enable/amplify corruptive effects.",
		mutations = "Naiad, Ent, Spriggan",
		pricemod = 2,
		#ralph5
		marketup = ["Demand for [color=aqua]dryads[/color] is up.\n","A noble house in the capitol has lavishly decorated their garden with topiaries of [color=aqua]dryads[/color] mixed in with the real thing and prices are up as the novelty catches on.\n"],
		marketdown = ["Rumors abound that sex with [color=aqua]dryads[/color] can give you splinters. Prices fall.\n"],
		single = " dryad",
		plural = " dryads",
		singlepos = " dryad's",
		pluralpos = " dryads'",
		#/ralph5
		startingrace = false,
		wimbornrace = false,
		gornrace = false,
		frostfordrace = false,
		banditrace = false,
		uncivilized = true,
		sebastian = true,
		shade = {male = "res://files/buttons/inventory/shades/Dryad_M.png", female = "res://files/buttons/inventory/shades/Dryad_F.png"},
		skin = ['green'],
		eyesclera = ['green'],
		haircolor = ['green', 'purple'],
		ears = ['pointy'],
		skincov = ['plants'],
		surname = '',
		stats = {	
			str_max = 3,	
			agi_max = 4,	
			maf_max = 5,	
			end_max = 4,	
		},
	},
	Dragonkin = {
		description = "Dragonkin are an extremely rare breed of human with draconic lineage, partially possessing the blood and certain physical traits of dragons, such as wings, scales, and a tail. While originally confined to the whims of dragons, a coalition of influential mages banded together and developed a powerful ritual to imbue grown humans with dragon blood, in spite of observed difficulties in adoption of the blood so late into development. There is a great deal of secrecy surrounding the ritual, and outside of a few involved elite, its success rate is unknown. The few dragonkin alleged to have been produced by the ritual are virtually indistinguishable from those who were naturally birthed.",
		details = "[color=aqua]Racial trait: natural avarice, usually Spoiled by nature.[/color]\n\n[color=yellow]Stat potential: Strength - {str_max}, Agility - {agi_max}, Magic - {maf_max}, Endurance - {end_max} [/color]",
		breedingnotes = "The creation of new Dragonkin is the pinnacle of modern transformative magic. Previously research subjects were only very rarely obtained, but now breeders on the cutting edge of racial husbandry within the guild are rushing to discover what potential might be manifest in Dragonkin hybrids. It is truly an exciting time to be a mage!",
		racialstatbonuses = "Strength++",
		purebloodbonus = "Magic+",
		otherracialcharacteristics = "Courage+, Demands luxury",
		elementalmod = {
			fire = 100,
			wind = 0,
			water = 0,
			earth = 0,
			nature = 50,
			corruption = 75,
		},
		elementalbonuses = "Fire (Agility+)",
		naturebonus = "Endurance+",
		highcorruptionbonus = "Magic+, Endurance-",
		lowcorruptionbonus = "Magic-, Endurance+, Demands less luxury",
		breedingquirk = "Females tend to be smaller and faster if not as strong.",
		mutations = "Salamander, Tiefling, Sharkkin",
		pricemod = 3.5,
		#ralph5
		marketup = ["Demand for [color=aqua]dragonkin[/color] is up.\n","Word is that an arena boss from across the sea has started an aerial league and has been looking to buy [color=aqua]dragonkin[/color].\n"],
		marketdown = ["Prices for [color=aqua]dragonkin[/color] fall as rumors that slave brands fail to prevent violence against their masters circulate.\n"],
		single = " dragon",
		plural = " dragons",
		singlepos = " dragon's",
		pluralpos = " dragons'",
		#/ralph5
		startingrace = false,
		wimbornrace = false,
		gornrace = false,
		frostfordrace = false,
		banditrace = false,
		uncivilized = false,
		sebastian = true,
		shade = {male = "res://files/buttons/inventory/shades/Dragonkin_M.png", female = "res://files/buttons/inventory/shades/Dragonkin_F.png"},
		eyecolor = ['amber', 'red', 'brown'],
		eyeshape = ['slit', 'normal'],
		haircolor = ['white', 'green', 'purple', 'blue', 'blond', 'red', 'auburn'],
		ears = ['pointy'],
		tail = ['dragon'],
		horns = ['short', 'long_straight', 'curved'],
		wings = ['leather_black', 'leather_red','leather_blue','leather_green','leather_white',],
		surname = '',
		skincov = ['scales'],
		scalecolor = ['red', 'blue', 'white', 'green', 'black', 'yellow'],
		arms = ['scales'],
		legs = ['scales'],
		stats = {	
			str_max = 6,	
			agi_max = 4,	
			maf_max = 5,	
			end_max = 5,	
		},
	},
	Taurus = {
		description = "Taurus are a purely artificial race, created on the orders of a group of noblemen looking for bodyguards. The experiment seems to have been an attempt at recreating the size and strength of orcs and beastkin in a more easily controlled package, but was ultimately considered only partially successful, as the new species had a tendency of taking too many bovine behavioral traits, becoming too passive, or in some cases, too aggressive.\n\nStill, they, especially the females, remain popular among certain individuals for their appearance and outstanding natural lactation.",
		details = "[color=aqua]Racial trait: milking is more effective. [/color]\n\n[color=yellow]Stat potential: Strength - {str_max}, Agility - {agi_max}, Magic - {maf_max}, Endurance - {end_max} [/color]",
		breedingnotes = "Research on Taurus is of course recent and they have been thoroughly studied. The only known mutation occurs when Taurus are bred to have both orcish and equine heritage, producing the hybrid commonly known as a Minotaur. Although pure Taurus are the most perfectly balanced pedigree, more aggressive or passive hybrids may also be produced by breeding with races of strong predator or prey origins.",
		racialstatbonuses = "Strength+, Endurance+",
		purebloodbonus = "Agility+",
		otherracialcharacteristics = "Fertility++",
		elementalmod = {
			fire = 0,
			wind = 0,
			water = 25,
			earth = 25,
			nature = 25,
			corruption = 50,
		},
		elementalbonuses = "Earth (Strength+)",
		naturebonus = "Endurance+",
		highcorruptionbonus = "Reversed predator/prey effects",
		lowcorruptionbonus = "Amplified predator/prey effects",
		breedingquirk = "Predator/Prey breeding determines strength vs sturdiness.",
		mutations = "Minotaur",
		pricemod = 2,
		#ralph5
		marketup = ["Demand for [color=aqua]tauruses[/color] is up.\n","A popular refreshment with a not so secret ingredient takes the capitol by storm. Demand for [color=aqua]tauruses[/color] is up.","[color=aqua]Taurus[/color] milk is finally catching on across the sea and entrepreneurs there are buying up available [color=aqua]tauruses[/color]. Prices increase.\n"],
		marketdown = ["Breeders seem to have gotten carried away acquiring [color=aqua]tauruses[/color] and demand tapers off.\n"],
		single = " taurus",
		plural = " tauruses",
		singlepos = " taurus'",
		pluralpos = " tauruses'",
		#/ralph5
		startingrace = true,
		wimbornrace = true,
		gornrace = true,
		frostfordrace = false,
		banditrace = true,
		uncivilized = false,
		sebastian = true,
		shade = {male = "res://files/buttons/inventory/shades/Taurus_M.png", female = "res://files/buttons/inventory/shades/Taurus_F.png"},
		horns = ['long_straight'],
		ears = ['short_furry'],
		tail = ['scruffy'],
		stats = {	
			str_max = 5,	
			agi_max = 3,	
			maf_max = 2,	
			end_max = 6,	
		}
	},
	Slime = {
		description = "Slimes are the result of a relatively common magical mutation, which dramatically changes a person's bodily integrity. Slimes are heavily reliant on water, even though their body is not actually 'slimy'. They can freely ooze over anything they touch, yet are in fact, pretty cohesive and firm to the touch.\n\nUnlike most other ooze-type slime monsters, slimes of humanoid origins are capable of nearly the same mental processes, although they are generally ill-regarded for having a clearly monstrous appearance.",
		details = "[color=aqua]Racial trait: can't be modified in the lab, toxicity is nullified every day.[/color]'\n\n[color=yellow]Stat potential: Strength - {str_max}, Agility - {agi_max}, Magic - {maf_max}, Endurance - {end_max} [/color]",
		breedingnotes = "Slimes are versatile and quite powerful lifeforms. The only form of reproduction observed to date involves the gruesome assimilation of an unborn being of another race, but breeders speculate that there must be another method of reproduction that is inherent.  It not totally certain if Slimes are naturally gendered or if they merely mimic other species. There have been no successful attempts to date resulting in proper Slime hybrids, but most agree that the mating process is nonetheless quite entertaining to observe and participate in.",
		racialstatbonuses = "",
		purebloodbonus = "",
		otherracialcharacteristics = "",
		elementalmod = {
			fire = 0,
			wind = 0,
			water = 0,
			earth = 0,
			nature = 0,
			corruption = 0,
		},
		elementalbonuses = "",
		naturebonus = "",
		highcorruptionbonus = "",
		lowcorruptionbonus = "",
		breedingquirk = "",
		mutations = "",
		pricemod = 2.5,
		#ralph5
		marketup = ["Demand for [color=aqua]slimes[/color] is up.\n","[color=aqua]Slime[/color] semen and vaginal secretions are being marketed by peddlers as a panacea for all manner of illnesses. Demand rises as the rich and sickly clamber to harvest fresh from the tap.\n"],
		marketdown = ["Rumors of [color=aqua]slimes[/color] eating infants cause demand for [color=aqua]slimes[/color] to fall.\n"],
		single = " slime",
		plural = " slimes",
		singlepos = " slime's",
		pluralpos = " slimes'",
		#/ralph5
		startingrace = false,
		wimbornrace = false,
		gornrace = false,
		frostfordrace = false,
		banditrace = false,
		uncivilized = true,
		sebastian = false,
		shade = {male = "res://files/buttons/inventory/shades/Slime_M.png", female = "res://files/buttons/inventory/shades/Slime_F.png"},
		bodyshape = ['jelly'],
		haircolor = ['jelly'],
		skin = ['jelly'],
		surname = '',
		stats = {	
			str_max = 4,	
			agi_max = 6,	
			maf_max = 3,	
			end_max = 3,	
		},
	},
	Lamia = {
		description = "Lamias are easily recognized and tend to be timid in their interactions, rarely showing themselves to majority of the population. Their population has been severely reduced by hunting and extermination expeditions launched by different races. Lamias are surprisingly intelligent, as the few captured and studied samples have shown.",
		details = "[color=aqua]Racial trait: Elongated Tongue.[/color]\n\n[color=yellow]Stat potential: Strength - {str_max}, Agility - {agi_max}, Magic - {maf_max}, Endurance - {end_max} [/color]",
		breedingnotes = "Though little organized study of Lamia crossbreeding has occured, it has been confirmed that the species is compatable with humanoids. Some breeders speculate that several unique mutations of Lamia are the source of various folklore and myths regarding intelligent monsters whose common physical attribute is the single foot or tail as opposed to a bipedal hindquarters.",
		racialstatbonuses = "Agility+, Magic+",
		purebloodbonus = "Endurance+",
		otherracialcharacteristics = "Confidence++",
		elementalmod = {
			fire = 25,
			wind = 0,
			water = 50,
			earth = 25,
			nature = 50,
			corruption = 50,
		},
		elementalbonuses = "Fire (Strength+), Water (Magic+), Earth (Endurance+)",
		naturebonus = "Magic+",
		highcorruptionbonus = "Strength-, Agility-, Magic+",
		lowcorruptionbonus = "Strength+, Agility+, Magic-",
		breedingquirk = "Double racial bonuses from predatory beast races.",
		mutations = "Merfolk, Naga, Slugkin",
		pricemod = 2.5,
		#ralph5
		marketup = ["Demand for [color=aqua]lamias[/color] is up.\n","A pornographic leaflet has been widely sold to young rich boys depicting [color=aqua]lamia[/color] performing very creative acts of oral sex. Every rich and noble teen boy and even some girls are begging their parents for [color=aqua]lamia[/color] playmates.\n"],
		marketdown = ["A dramatized story of a [color=aqua]lamia[/color] who ate her master in the capitol is spreading like wildfire. Demand for [color=aqua]lamias[/color] is down.\n"],
		single = " lamia",
		plural = " lamias",
		singlepos = " lamia's",
		pluralpos = " lamias'",
		#/ralph5
		startingrace = false,
		wimbornrace = false,
		gornrace = false,
		frostfordrace = false,
		banditrace = false,
		uncivilized = true,
		sebastian = false,
		shade = {male = "res://files/buttons/inventory/shades/Lamia_M.png", female = "res://files/buttons/inventory/shades/Lamia_F.png"},
		bodyshape = ['halfsnake'],
		haircolor = ['white', 'green', 'purple', 'blue', 'blond', 'red', 'auburn'],
		tail = ['snake tail'],
		ears = ['pointy'],
		skincov = ['scales'],
		scalecolor = ['red', 'blue', 'white', 'green', 'black', 'yellow'],
		legs = ['snake'],
		eyecolor = ['blue', 'green', 'amber', 'red'],
		eyeshape = ['slit'],
		surname = '',
		mods = {augmenttongue = 'augmenttongue'},
		stats = {	
			str_max = 4,	
			agi_max = 5,	
			maf_max = 4,	
			end_max = 4,	
		}
	},
	Harpy = {
		description = "Harpies are human-bird hybrids with easily recognisable features, such as their feathered arms and avian lower quarters. Commonly seen as monsters, they have existed since time immemorial. Wild harpies generally inhabit mountain regions and are relatively aggressive. Their intelligence has a wide range, and people have had some success making them into slave-pets.",
		details = "[color=aqua]Racial trait: egg-laying is more effective.[/color]\n\n[color=yellow]Stat potential: Strength - {str_max}, Agility - {agi_max}, Magic - {maf_max}, Endurance - {end_max} [/color]",
		breedingnotes = "Most study into Harpy breeding has been focused on enhanced physical characteristics. The most successful attempts have involved combining them with one or more predatory beastkin species. Additionally, it is widely assumed that the Harpy's prolific egg laying could be harnessed to enhance the fertility of other egg laying races.",
		racialstatbonuses = "Agility++",
		purebloodbonus = "Strength+",
		otherracialcharacteristics = "Fertility++, Courage++, Height-, Lewdness+ (females)",
		elementalmod = {
			fire = 0,
			wind = 100,
			water = 0,
			earth = 0,
			nature = 50,
			corruption = 75,
		},
		elementalbonuses = "Wind (Magic+)",
		naturebonus = "Magic+",
		highcorruptionbonus = "Strength+, Magic-",
		lowcorruptionbonus = "Strength-, Magic+",
		breedingquirk = "Strength+, Agility+ from breeding with predatory beast races/nFertility+ as a secondary race for egg-laying races.",
		mutations = "Gargoyle",
		pricemod = 2.5,
		#ralph5
		marketup = ["Demand for [color=aqua]harpies[/color] is up.\n","The popularity of a play featuring a dastardly human villain enslaving a cute transforming [color=aqua]harpy[/color] princess to pull his wagon facinates the masses. Demand for [color=aqua]harpies[/color] increases.\n","Word is that an arena boss from across the sea has started an aerial league and has been buying up [color=aqua]harpies[/color].\n"],
		marketdown = ["Rumors abound that [color=aqua]harpies[/color] are rife with disease. Demand decreases.\n"],
		single = " harpy",
		plural = " harpies",
		singlepos = " harpy's",
		pluralpos = " harpies'",
		#/ralph5
		startingrace = false,
		wimbornrace = false,
		gornrace = true,
		frostfordrace = false,
		banditrace = false,
		uncivilized = true,
		sebastian = false,
		shade = {male = "res://files/buttons/inventory/shades/Harpy_M.png", female = "res://files/buttons/inventory/shades/Harpy_F.png"},
		bodyshape = ['halfbird'],
		haircolor = ['white', 'green', 'purple', 'blue', 'blond', 'red', 'auburn'],
		tail = ['bird'],
		ears = ['feathery'],
		skincov = ['feathers'],
		arms = ['winged'],
		legs = ['avian'],
		surname = '',
		stats = {	
			str_max = 4,	
			agi_max = 5,	
			maf_max = 3,	
			end_max = 3,	
		},
	},
	Arachna = {
		description = "Arachna live in isolation and tend to choose caves and other underground locations as their homes. While not being especially aggressive, they are fearsome hunters and have been reported for rare night attacks on both cattle and humans.",
		details = "[color=aqua]Racial trait: hunting is more effective.[/color]\n\n[color=yellow]Stat potential: Strength - {str_max}, Agility - {agi_max}, Magic - {maf_max}, Endurance - {end_max} [/color]",
		breedingnotes = "Arachna are quite rare and few breeders have had the opportunity to mate Arachna with more exotic species so more experimentation is needed.",
		racialstatbonuses = "Strength+, Endurance+",
		purebloodbonus = "Magic+",
		otherracialcharacteristics = "Females are considerably larger than males",
		elementalmod = {
			fire = 0,
			wind = 25,
			water = 0,
			earth = 50,
			nature = 50,
			corruption = 75,
		},
		elementalbonuses = "Wind (Agility+), Earth (Endurance+)",
		naturebonus = "Magic++",
		highcorruptionbonus = "Strength-, Agility+",
		lowcorruptionbonus = "Strength+, Agility-",
		breedingquirk = "None",
		mutations = "Crabkin, Bee",
		pricemod = 2.5,
		#ralph5
		marketup = ["Demand for [color=aqua]arachnas[/color] is up.\n","News is that a weaver in Frostford has been selling designer silks spun from [color=aqua]arachna[/color] webbing. Prices for [color=aqua]arachnas[/color] have increased.\n"],
		marketdown = ["Rumors abound that insect-like species of any sex implant eggs in their partners. Demand for [color=aqua]arachnas[/color] falls.\n"],
		single = " arachna",
		plural = " arachnas",
		singlepos = " arachna's",
		pluralpos = " arachnas'",
		#/ralph5
		startingrace = false,
		wimbornrace = false,
		gornrace = false,
		frostfordrace = false,
		banditrace = false,
		uncivilized = true,
		sebastian = false,
		shade = {male = "res://files/buttons/inventory/shades/Arachna_M.png", female = "res://files/buttons/inventory/shades/Arachna_F.png"},
		bodyshape = ['halfspider'],
		haircolor = ['white', 'green', 'purple', 'blue', 'blond', 'red', 'auburn'],
		tail = ['spider abdomen'],
		ears = ['pointy'],
		skincov = ['scales'],
		legs = ['spider'],
		eyecolor = ['blue', 'green', 'amber', 'red'],
		eyeshape = ['slit'],
		surname = '',
		stats = {	
			str_max = 4,	
			agi_max = 4,	
			maf_max = 5,	
			end_max = 4,	
		},
	},
	Centaur = {
		description = "The Centaur race is somewhat distant, yet not unheard of in southern regions. Some individuals have made it very far by adopting a nomadic lifestyle, making the race common enough to be recognized by most. The centauri population is relatively small, due to dealing with territorial oppression from humanoid races.",
		details = "[color=aqua]Racial trait: Increased Energy.[/color]\n\n[color=yellow]Stat potential: Strength - {str_max}, Agility - {agi_max}, Magic - {maf_max}, Endurance - {end_max} [/color]",
		breedingnotes = "Centaur make poor spellcasters, but are potent as warriors. Their stubborn tendency toward isolation and refusal to sell their kind into slavery makes study into Centaur hybrids a challenge. When available however, they are prized for their use as the minority race in hybrids to enhance various male attributes.",
		racialstatbonuses = "Agility+, Endurance+",
		purebloodbonus = "Endurance+",
		otherracialcharacteristics = "Courage++",
		elementalmod = {
			fire = 0,
			wind = 0,
			water = 0,
			earth = 25,
			nature = 50,
			corruption = 50,
		},
		elementalbonuses = "Earth (Strength+)",
		naturebonus = "Physical attributes based on races bred with.",
		highcorruptionbonus = "Strength+, Magic--, Endurance+",
		lowcorruptionbonus = "Strength-, Magic++, Endurance-",
		breedingquirk = "Breeding with shortstacks is not advised.",
		mutations = "Pegasus, Bicorn, Kelpie",
		pricemod = 1.5,
		#ralph5
		marketup = ["Demand for [color=aqua]centaurs[/color] is up.\n","Demand for [color=aqua]centaurs[/color] is up as they become popular combination escorts and mounts.\n"],
		marketdown = ["Prices for [color=aqua]centaurs[/color] drops as equine sex enthusiasts realize they can buy horses for less and without any of the backtalk.\n"],
		single = " centaur",
		plural = " centaurs",
		singlepos = " centaur's",
		pluralpos = " centaurs'",
		#/ralph5
		startingrace = false,
		wimbornrace = false,
		gornrace = true,
		frostfordrace = false,
		banditrace = false,
		uncivilized = false,
		sebastian = true,
		shade = {male = "res://files/buttons/inventory/shades/Centaur_M.png", female = "res://files/buttons/inventory/shades/Centaur_F.png"},
		bodyshape = ['halfhorse'],
		tail = ['horse'],
		ears = ['short_furry'],
		legs = ['horse'],
		stats = {	
			str_max = 5,	
			agi_max = 5,	
			maf_max = 3,	
			end_max = 5,	
			energy_max = 140,	
		},
	},
	Nereid = {
		description = "Nereid are considered to be another subspecies of the humanoid races, yet they likely split from another race in the distant past. They adapted to an aquatic lifestyle. Nereids are often seen by sailors and fishermen, but they tend to be hesitant in making contact with humans, likely viewing them as a threat.",
		details = "[color=aqua]Racial trait: entertainment is more effective.[/color]\n\n[color=yellow]Stat potential: Strength - {str_max}, Agility - {agi_max}, Magic - {maf_max}, Endurance - {end_max} [/color]",
		breedingnotes = "Aside from collected efforts by fisherman at trapping and enslaving Nereids, collecting viable specimens for breeding has rarely been accomplished; however there have been recent sightings of Nereids visiting the shores Southwest of Wimborn. Mages are encouraged to aquire these sea nymphs for extended study, though pricing can be expected to be driven by high demand.",
		racialstatbonuses = "Magic++",
		purebloodbonus = "Magic+",
		otherracialcharacteristics = "Beauty++, Courage-, Charm+",
		elementalmod = {
			fire = 0,
			wind = 0,
			water = 100,
			earth = 0,
			nature = 50,
			corruption = 50,
		},
		elementalbonuses = "Water (Strength+)",
		naturebonus = "Magic- (land-based nature magic incompatible)",
		highcorruptionbonus = "Magic+, Endurance-, Beauty-",
		lowcorruptionbonus = "Magic-, Endurance+, Beauty+",
		breedingquirk = "Adapts better to land when bred with reptilian species",
		mutations = "Frogkin, Toadkin, Kappa, Lobsterman, Ciguapa",
		pricemod = 2.5,
		#ralph5
		marketup = ["Demand for [color=aqua]nereids[/color] is up.\n","Seafood is in season and prices for [color=aqua]nereids[/color] are up.","A new fad amongst nobles is to employ all aquatic servants and throw undersea balls. Demand for [color=aqua]nereids[/color] is up.\n"],
		marketdown = ["Rumors abound that all [color=aqua]nereids'[/color] genitalia reeks of dead fish. Prices fall.\n"],
		single = " nereid",
		plural = " nereids",
		singlepos = " nereid's",
		pluralpos = " nereids'",
		#/ralph5
		startingrace = false,
		wimbornrace = false,
		gornrace = false,
		frostfordrace = false,
		banditrace = false,
		uncivilized = true,
		sebastian = false,
		shade = {male = "res://files/buttons/inventory/shades/Nereid_M.png", female = "res://files/buttons/inventory/shades/Nereid_F.png"},
		bodyshape = ['halffish'],
		tail = ['fish'],
		ears = ['fins'],
		legs = ['webbed'],
		arms = ['webbed'],
		eyecolor = ['amber', 'red', 'turquoise'],
		eyeshape = ['slit'],
		eyesclera = ['yellow'],
		skin = ['teal', 'blue', 'pale blue'],
		surname = '',
		stats = {	
			str_max = 3,	
			agi_max = 5,	
			maf_max = 5,	
			end_max = 3,	
		},
	},
	Scylla = {
		bodyshape = ['halfsquid'],
		description = "Scylla are rather unusual in appearance, possessing a number of tentacle-like appendages they use in the place of legs. They generally prefer damp and aquatic regions. In general, their behavior is not much different from lamia. Their appearance is extremely rare, to the point of being treated as mere myth or drunken fancy by some.",
		details = "[color=aqua]Racial trait: cooking is more effective.[/color]\n\n[color=yellow]Stat potential: Strength - {str_max}, Agility - {agi_max}, Magic - {maf_max}, Endurance - {end_max} [/color]",
		breedingnotes = "Unfortunately due to extreme scarceness, very little is known of these creatures and recorded research is dubious, likely consisting of as much rumor as fact.",
		racialstatbonuses = "Agility+, Magic+",
		purebloodbonus = "Strength+",
		otherracialcharacteristics = "Confidence++",
		elementalmod = {
			fire = 0,
			wind = 0,
			water = 75,
			earth = 0,
			nature = 25,
			corruption = 75,
		},
		elementalbonuses = "Water (Magic+)",
		naturebonus = "Endurance+",
		highcorruptionbonus = "Strength++, Magic-, Confidence+",
		lowcorruptionbonus = "Strength-, Magic++, Confidence--",
		breedingquirk = "Stats+ from breeding with many-legged races.",
		mutations = "Tentacle, Alraune",
		pricemod = 2.5,
		#ralph5
		marketup = ["Demand for [color=aqua]scyllas[/color] is up.\n","Seafood is in season and prices for [color=aqua]scyllas[/color] are up.","A new fad amongst nobles is to employ all aquatic servants and throw undersea balls. Demand for [color=aqua]scyllas[/color] is up.\n"],
		marketdown = ["Rumors abound that all [color=aqua]scyllas'[/color] genitalia reeks of dead fish. Prices fall.\n"],
		single = " scylla",
		plural = " scyllas",
		singlepos = " scylla's",
		pluralpos = " scyllas'",
		#/ralph5
		startingrace = false,
		wimbornrace = false,
		gornrace = false,
		frostfordrace = false,
		banditrace = false,
		uncivilized = true,
		sebastian = false,
		shade = {male = "res://files/buttons/inventory/shades/Scylla_M.png", female = "res://files/buttons/inventory/shades/Scylla_F.png"},
		tail = ['tentacles'],
		ears = ['pointy'],
		legs = ['tentacles'],
		eyecolor = ['blue', 'green', 'amber', 'red'],
		surname = '',
		stats = {	
			str_max = 5,	
			agi_max = 4,	
			maf_max = 5,	
			end_max = 4,	
		},
	},
	"Beastkin Cat" : {
		bodyshape = ['bestial'],
		description = "Cat folk are an unusually social breed of Beastkin, having no known settlements of their own, and living quite openly in populous towns and cities. They have a great deal of popularity among certain crowds for their lush appearance and lascivious nature.",
		details = "[color=aqua]Racial trait: increased dodge chance.[/color]\n\n[color=yellow]Stat potential: Strength - {str_max}, Agility - {agi_max}, Magic - {maf_max}, Endurance - {end_max} [/color]",
		breedingnotes = "As one of the original beastkin races developed by the early Mage Order, catkin have been thoroughly studied and many breeders contend there is little point to further research.  That said, with so many new sexually compatible races having been discovered recently, perhaps there is more to learn.",
		racialstatbonuses = "Strength+, Agility+",
		purebloodbonus = "Strength+",
		otherracialcharacteristics = "Charm+",
		elementalmod = {
			fire = 0,
			wind = 25,
			water = 0,
			earth = 0,
			nature = 50,
			corruption = 25,
		},
		elementalbonuses = "Wind (Agility+)",
		naturebonus = "Endurance+",
		highcorruptionbonus = "Strength+, Endurance-",
		lowcorruptionbonus = "Strength-, Endurance+",
		breedingquirk = "None",
		mutations = "Manticore, Nekomata",
		pricemod = 1.75,
		#ralph5
		marketup = ["Demand for [color=aqua]catkin[/color] is up.\n","Rumors concerning the supposed superiority of feline genitalia abound. Demand for [color=aqua]catkin[/color] increases.\n"],
		marketdown = ["Irresponsible pet owners fail to spay and neuter. There are just more[color=aqua]catkin[/color] on the market than buyers.\n"],
		single = " catkin",
		plural = " catkin",
		singlepos = " cat's",
		pluralpos = " cats'",
		#/ralph5
		startingrace = true,
		wimbornrace = true,
		gornrace = true,
		frostfordrace = true,
		banditrace = true,
		uncivilized = false,
		sebastian = true,
		shade = {male = "res://files/buttons/inventory/shades/Beastkin-Cat_M.png", female = "res://files/buttons/inventory/shades/Beastkin-Cat_F.png"},
		skincov = ['full_body_fur'],
		furcolor = ['white', 'gray', 'orange_white','black_white','black_gray','black'],
		tail = ['cat'],
		ears = ['short_furry'],
		legs = ['fur_covered'],
		arms = ['fur_covered'],
		eyecolor = ['blue', 'green', 'amber', 'red'],
		eyeshape = 'slit',
		stats = {	
			str_max = 4,	
			agi_max = 6,	
			maf_max = 3,	
			end_max = 3,	
		},
	},
	"Beastkin Fox" : {
		bodyshape = ['bestial'],
		description = "Fox folk are a rare, and relatively mysterious breed of Beastkin. They display high intelligence, a tendency towards lifelong monogamy, and congregate in small, close-knit communities.",
		details = "[color=aqua]Racial trait: escort assignment is more effective.[/color]\n\n[color=yellow]Stat potential: Strength - {str_max}, Agility - {agi_max}, Magic - {maf_max}, Endurance - {end_max} [/color]",
		breedingnotes = "Although thought to have originated near the same time as the original beastkin races developed by the early Mage Order, foxkin tended to hide from communities and are only rarely encountered.  They are known for their adroitness and have a significant affinity for magic.",
		racialstatbonuses = "Agility++",
		purebloodbonus = "Magic+",
		otherracialcharacteristics = "Beauty+, Wit+, Charm+",
		elementalmod = {
			fire = 25,
			wind = 0,
			water = 0,
			earth = 0,
			nature = 75,
			corruption = 25,
		},
		elementalbonuses = "Fire (Magic+)",
		naturebonus = "Strength-, Agility+, Magic+",
		highcorruptionbonus = "Magic+",
		lowcorruptionbonus = "Magic+",
		breedingquirk = "None",
		mutations = "Kitsune",
		pricemod = 2,
		#ralph5
		marketup = ["Demand for [color=aqua]foxkin[/color] is up.\n","Demand for foxy bedwarmers is up. Prices for [color=aqua]foxkin[/color] increase.\n"],
		marketdown = ["Rumors abound that [color=aqua]foxkin[/color] have the mysterious ability to escape their owners at will despite slave brands and restraints. Prices fall.\n"],
		single = " foxkin",
		plural = " foxkin",
		singlepos = " fox's",
		pluralpos = " foxes'",
		#/ralph5
		startingrace = true,
		wimbornrace = false,
		gornrace = false,
		frostfordrace = true,
		banditrace = false,
		uncivilized = false,
		sebastian = true,
		shade = {male = "res://files/buttons/inventory/shades/Beastkin-Fox_M.png", female = "res://files/buttons/inventory/shades/Beastkin-Fox_F.png"},
		skincov = ['full_body_fur'],
		furcolor = ['black_white', 'orange', 'orange', 'orange'],
		tail = ['fox'],
		ears = ['long_pointy_furry'],
		legs = ['fur_covered'],
		arms = ['fur_covered'],
		eyecolor = ['blue', 'green', 'amber', 'red'],
		eyeshape = ['slit'],
		stats = {	
			str_max = 4,	
			agi_max = 5,	
			maf_max = 4,	
			end_max = 3,	
		},
	},
	"Beastkin Wolf" : {
		bodyshape = ['bestial'],
		description = "Unlike other Beastkin, Wolves are not viewed as simple novelties, but are treated as the powerful, agile pack hunters they are. Though they rarely show hostility towards outsiders unless threatened, great caution should be taken when dealing with them.\n\nThere are rumors that far to the north exists a nation richly populated by Beastkin, where wolves play a leading role, being well suited to the harsh environment.",
		details = "[color=aqua]Racial trait: Detection bonus, Combat Power increased.[/color]\n\n[color=yellow]Stat potential: Strength - {str_max}, Agility - {agi_max}, Magic - {maf_max}, Endurance - {end_max} [/color]",
		breedingnotes = "As one of the original beastkin races developed by the early Mage Order, wolfkin have been thoroughly studied and many breeders contend there is little point to further research. That said, with so many new sexually compatible races having been discovered recently, perhaps there is more to learn.",
		racialstatbonuses = "Stength+, Agility+",
		purebloodbonus = "Endurance+",
		otherracialcharacteristics = "Courage+",
		elementalmod = {
			fire = 25,
			wind = 0,
			water = 0,
			earth = 0,
			nature = 50,
			corruption = 25,
		},
		elementalbonuses = "Fire (Strength+)",
		naturebonus = "Endurance+",
		highcorruptionbonus = "Agility-, Endurance+",
		lowcorruptionbonus = "Agility+, Endurance-",
		breedingquirk = "None",
		mutations = "Infernus, Dog, Werewolf",
		pricemod = 1.75,
		#ralph5
		marketup = ["Demand for [color=aqua]wolfkin[/color] is up.\n"],
		marketdown = ["Irresponsible pet owners fail to spay and neuter. There are just more [color=aqua]wolfkin[/color] on the market than buyers.\n"],
		single = " wolfkin",
		plural = " wolfkin",
		singlepos = " wolf's",
		pluralpos = " wolves'",
		#/ralph5
		startingrace = true,
		wimbornrace = true,
		gornrace = false,
		frostfordrace = true,
		banditrace = true,
		uncivilized = false,
		sebastian = true,
		shade = {male = "res://files/buttons/inventory/shades/Beastkin-Wolf_M.png", female = "res://files/buttons/inventory/shades/Beastkin-Wolf_F.png"},
		skincov = ['full_body_fur'],
		furcolor = ['gray', 'black_gray', 'brown'],
		tail = ['wolf'],
		ears = ['short_furry'],
		legs = ['fur_covered'],
		arms = ['fur_covered'],
		eyecolor = ['blue', 'green', 'amber', 'red'],
		eyeshape = ['slit'],
		stats = {	
			str_max = 5,	
			agi_max = 5,	
			maf_max = 2,	
			end_max = 4,	
		},
	},
	"Beastkin Bunny" : {
		bodyshape = ['bestial'],
		description = "Bunnies are one of the least self-sufficient, but netherless common beast races. They are not aggressive and can actually be quite timid. They are quite well liked  due to their comforting appearance and their natural lewdness makes them a popular choice for slave pets.",
		details = "[color=aqua]Racial trait: prostitution related assignments cause only half stress.[/color]\n\n[color=yellow]Stat potential: Strength - {str_max}, Agility - {agi_max}, Magic - {maf_max}, Endurance - {end_max} [/color]",
		breedingnotes = "Bunnykin are thought to have originated near the same time as the original beastkin races developed by the early Mage Order. They have been thoroughly studied and many breeders contend there is little point to further research. That being said, they are still exceedingly popular with merchant breeders supplying brothels throughout the continent, though as a result of their enthusiasm for breeding it can sometimes be difficult to procure a pure specimen.",
		racialstatbonuses = "Agility++",
		purebloodbonus = "Endurance+",
		otherracialcharacteristics = "Courage-, Fertility+++, Pliability+, Lewdness++",
		elementalmod = {
			fire = 0,
			wind = 0,
			water = 0,
			earth = 50,
			nature = 50,
			corruption = 25,
		},
		elementalbonuses = "Earth (Endurance+)",
		naturebonus = "Amplifies physical attribute bonuses from races bred with.",
		highcorruptionbonus = "Amplifies sexual features from races bred with.",
		lowcorruptionbonus = "Reduces sexual feature bonuses from races bred with.",
		breedingquirk = "Typically provide a good example for breeding stock.",
		mutations = "None",
		pricemod = 1.75,
		#ralph5
		marketup = ["Demand for [color=aqua]bunnykin[/color] is up.\n"],
		marketdown = ["Irresponsible pet owners fail to spay and neuter. There are just more [color=aqua]bunnykin[/color] on the market than buyers.\n","Rumors abound that [color=aqua]bunnykin[/color] simply aren't all that in the sack. Prices fall.\n"],
		single = " bunnykin",
		plural = " bunnykin",
		singlepos = " bunny's",
		pluralpos = " bunnies'",
		#/ralph5
		startingrace = false,
		wimbornrace = false,
		gornrace = true,
		frostfordrace = true,
		banditrace = false,
		uncivilized = false,
		sebastian = true,
		shade = {male = "res://files/buttons/inventory/shades/Beastkin-Bunny_M.png", female = "res://files/buttons/inventory/shades/Beastkin-Bunny_F.png"},
		skincov = ['full_body_fur'],
		furcolor = ['white', 'gray'],
		tail = ['bunny'],
		ears = ['long_round_furry', 'long_droopy_furry'],
		legs = ['fur_covered'],
		arms = ['fur_covered'],
		eyecolor = ['blue', 'green', 'amber', 'red'],
		stats = {	
			str_max = 3,	
			agi_max = 5,	
			maf_max = 3,	
			end_max = 3,	
		},
	},
	"Beastkin Tanuki" : {
		bodyshape = ['bestial'],
		description = "The Tanuki are a rare beast race possessing raccoon features. It's hard to pinpoint any specific mental differences between them and the majority of the humanoid races. Some say that their behavior and attitudes are much like that of the average human. There's still much  speculation as to how they originated.",
		details = "[color=aqua]Racial trait: store assignment more effective.[/color]\n\n[color=yellow]Stat potential: Strength - {str_max}, Agility - {agi_max}, Magic - {maf_max}, Endurance - {end_max}",
		breedingnotes = "Tanuki are thought to have originated near the same time as the original beastkin races developed by the early Mage Order.  They tend to congregate and interact similar to humans but typically in seclusion.  As such they have not been studied as thoroughly as the guild would like. They are typically highly magically attuned and rumor has it that remote Tanuki communities practice some form of temporary transformative magic though the guild dismisses this as preposterous.",
		racialstatbonuses = "Magic++",
		purebloodbonus = "Endurance+",
		otherracialcharacteristics = "Wit++",
		elementalmod = {
			fire = 0,
			wind = 25,
			water = 0,
			earth = 0,
			nature = 75,
			corruption = 25,
		},
		elementalbonuses = "Wind (Agility+)",
		naturebonus = "Strength+, Magic+, Endurance+ subject to quirk",
		highcorruptionbonus = "Magic-, Endurance+",
		lowcorruptionbonus = "Magic+, Endurance-",
		breedingquirk = "Nature bonus when bred with forest guarding races.",
		mutations = "Werebear",
		pricemod = 1.75,
		#ralph5
		marketup = ["Demand for [color=aqua]tanuki[/color] is up.\n","The popularity of a play involving a dastardly human villain dragging around a cute smitten [color=aqua]tanuki[/color] slave girl facinates the masses. Demand for [color=aqua]tanuki[/color] increases.\n"],
		marketdown = ["Rumors abound that [color=aqua]tanuki[/color] have the mysterious ability to escape their owners at will despite slave brands and restraints. Prices fall.\n","Rumor of a [color=aqua]tanuki[/color] crushing his master with testicles spread and the market shrinks.\n"],
		single = " tanuki",
		plural = " tanukis",
		singlepos = " tanuki's",
		pluralpos = " tanukis'",
		#/ralph5
		startingrace = false,
		wimbornrace = false,
		gornrace = false,
		frostfordrace = true,
		banditrace = false,
		uncivilized = false,
		sebastian = true,
		shade = {male = "res://files/buttons/inventory/shades/Beastkin-Tanuki_M.png", female = "res://files/buttons/inventory/shades/Beastkin-Tanuki_F.png"},
		skincov = ['full_body_fur'],
		furcolor = ['black_gray'],
		tail = ['racoon'],
		ears = ['short_furry'],
		legs = ['fur_covered'],
		arms = ['fur_covered'],
		eyecolor = ['blue', 'green', 'amber', 'red'],
		eyeshape = ['slit'],
		stats = {	
			str_max = 4,	
			agi_max = 4,	
			maf_max = 4,	
			end_max = 4,	
		},
	},
}

var beastkindescription = "The term Beastkin refers to a wide range of sentient species with prominent humanoid and animalistic traits. True beastkin are fully covered in fur, feathers, or scales, with similar stature and proportions to a human. Even among individual species, there are wide differences to be observed with inherited animal traits, such as eyes, claws, and teeth. It is unknown whether Beastkin are man-made or the product of nature, as their spread and diversity often leads to inconsistent findings."
var halfkindescription = "Halfkin are the offspring produced by the union of a beastkin and a human. Halfkin most prominently display their human lineage, lacking fur and other major animalistic characteristics, but do possess secondary traits from their beastkin forebears, such as claws, ears, and tails, and tend to exhibit behavior from both parents equally.\n\nThe fate of halfkin varies from place to place, some living normally as any other race, others living under persecution and prejudice, and even rumors of far off lands where they are respected and worshipped. Regardless of what kind of environment they live in, halfkin are a popular item among collectors for their exotic appearance and the unique quality that their offspring will often swing back to fully human or fully beast."
