### <CustomFile> ###
extends Node

#---DimCrystal
#Intro
var dimcrystal_intro_0 = "While walking down a side corridor of your manor, you suddenly stop as a strange sensation runs up your spine. Turning to the wall, you notice an old mural detailing some fantastical battle. Examining the area more closely, you notice a small protrusion. You pull gently at it, hear a small click, and the section of wall silently swings open."

var dimcrystal_intro_1 = "Peering inside, you find an old spiral staircase leading down. A hidden cellar perhaps? The stonework is older than the rest of the manor and you can't yet decipher why magic would be wasted to create these beautiful enchanted lights for such a stairwell. Even with your uncle's supposed wealth it seems like a frivolous expense.\n\nAt the bottom of the stairs is a dim corridor. You descend it and find that it ends in a weathered, dark-brown wooden door lacking any doorknob that you can see. It is engraved with light purple faintly visible runes that you immediately recognize as powerful, permanent magic sigils. From what you can tell, those runes seem like very old magic and even the linework of the runes seem like distant ancestors of modern magical standards.\n\nYou take off your footwear, press it against the door cautiously, and the door does not budge. You put your footwear back on before you very cautiously reach forward and press your hand to the door. Surprisingly, the door swings wide open with no resistance whatsoever the moment your hands touch the flickering purple runes. The room beyond is pitch black with the same solid stone flooring beneath your feet stretching as far as you can see into the darkness. The air blowing out from within feels cool yet oddly crisp like the breeze on a cold winter's morning."

var dimcrystal_intro_2 = "You cautiously enter and find your attention is immediately drawn to the only visible object in the room. Centered within the massive chamber that seems far too large to be located beneath your Mansion is an enormous [color=#E389B9]Crystal[/color] suspended in the air. It perfectly hovers in what appears to be the dead center of the large, smooth stone room. You realize that only the light reflecting from the blue magical lamps in the stairway reflect tiny beams through the dark crystalline prism.\n\nYou step closer towards the [color=#E389B9]Crystal[/color] while feeling a strange sense of belonging encompass you the closer you approach it. You are certain that there are no records of this object or chamber in the mansion's deeds or blueprints. This secret room may have lain here unnoticed for generations for all you know.\n\nYou continue your approach and hear the faintest sounds of tingling and the very faintest of humming sounds in the back of your mind. You feel your feet carry you to the crystal and you press your hand against it with a rising certainty and sensation of power. You feel the dormant magic humming softly deep within the [color=#E389B9]Crystal[/color] through your fingertips."

var dimcrystal_intro_3 = "You feel your magic surge into the strange [color=#E389B9]Crystal[/color] as it eagerly laps up the secret essense of mana within you. You feel it respond to your gift with a growing light and increasing vibrations within it, though they are still faint. The object glows dimly and you feel an immediate connection to it. You have a certainty that this object is the catalyst for powers beyond what any normal mortal could accomplish with modern magic.\n\nYou feel that having given it your magic may have bonded it to you, allowing only you and those you desire to interact with it. You believe that you could commission contractors that you trust to [color=aqua]Upgrade[/color] the powers of the [color=#E389B9]Crystal[/color] by cleaning, polishing, and smoothing out the minor scuffs and damages it has received over time. You believe that between upgrading it, researching it, and resting to understand it, you will be able to master the powers it could grant you.\n\n[color=lime]You can now visit the [color=#E389B9]Crystal[/color] at any time via the picture of it on the main Mansion screen. You will have to [color=aqua]Upgrade[/color] it to at least [color=aqua]Tier 1[/color] to begin researching or utilizing it.[/color]"

#Darkened
var dimcrystal_dark_0 = "You feel it deep within you...something is wrong with the [color=#E389B9]Crystal[/color]. You feel a strange gnawing hunger in the pit of your stomach any time you try to reach out and touch any of the purplish energy you see infused throughout the house.\n\nYou decide to check on it immediately. From the moment your foot strikes the first step of the stairs, the sensation of gnawing hunger increases. The once-steady magical lighting on the stairs seems to flicker slightly, an unsettling and strange change. There are little trails of light from each of the light sources all heading towards the middle of the chamber as though the light is being ever so slightly pulled towards the [color=#E389B9]Crystal[/color]. You force yourself to press on into the massive smooth stone chamber housing the [color=#E389B9]Crystal[/color]."

var dimcrystal_dark_1 = "In the center of the room, the [color=#E389B9]Crystal[/color] pulses with sickening reddish light. You feel the odd sensation of emptiness spread from just within your stomach all throughout your body. You can tell that the [color=#E389B9]Crystal[/color] is sharing its needs with you. It feels intensely like the [color=#E389B9]Crystal[/color] is... hungry?\n\nYou think back on how you've used the powers granted to you by the [color=#E389B9]Crystal[/color] and realize you've been, intentionally or not, consuming more of its lifeforce than it can naturally replenish. You can't help but wonder if the [color=#E389B9]Crystal[/color] will start to react differently to being touched now? Is it still safe to research?\n\nThe [color=#E389B9]Crystal[/color] could be dangerous to use in its current condition until it is repaired and restored. There might also be advantages to using it in this dark and broken state, however. Either way, you feel confident that you shouldn't use the [color=#E389B9]Darkened Crystal[/color] on anyone that you care about."
