
extends Node

#warning-ignore:unused_class_variable
var abilitydict = {
	attack = {
		name = 'Attack',
		code = 'attack',
		iconnorm = load("res://files/buttons/abils/Attack.png"),
		iconpressed = load("res://files/buttons/abils/Attack3.png"),
		icondisabled = load("res://files/buttons/abils/Attack2.png"),
		learnable = false,
		description = 'Attempts to attack chosen enemy.',
		usetext = '$name goes for straight hit. ',
		target = 'one',
		targetgroup = 'enemy',
		effect = null,
		can_miss = true,
		power = 1,
		cooldown = 0,
		type = 'physical',
		price = 0,
		costenergy = 0,
		costmana = 0,
		costother = '',
		attributes = ['damage'],
		reqs = {level = 0},
		aipatterns = ['attack'],
		aitargets = '1enemy',
		aiselfcond = 'any',
		aitargetcond = 'any',
		aipriority = 1,
		castersfx = 'attackanimation',
	},
	"pass" : {
		name = 'Pass',
		code = 'pass',
		learnable = false,
		description = 'Do nothing.',
		usetext = '$name does nothing. ',
		target = 'self',
		targetgroup = 'ally',
		effect = null,
		can_miss = false,
		power = 0,
		cooldown = 0,
		type = 'physical',
		price = 0,
		costenergy = 0,
		costmana = 0,
		costother = '',
		attributes = [],
		reqs = {level = 0},
	},
	escape = {
		name = 'Escape',
		code = 'escape',
		iconnorm = load("res://files/buttons/abils/Escape.png"),
		iconpressed = load("res://files/buttons/abils/Escape3.png"),
		icondisabled = load("res://files/buttons/abils/Escape2.png"),
		learnable = false,
		description = 'Attempts to escape from the fight.',
		usetext = '$name tries to escape from the fight. ',
		target = 'self',
		targetgroup = 'ally',
		effect = 'escapeeffect',
		can_miss = false,
		power = 1,
		cooldown = 4,
		type = 'physical',
		price = 0,
		costenergy = 10,
		costmana = 0,
		costother = '',
		attributes = [],
		reqs = {level = 0},
		aipatterns = ['any'],
		aitargets = 'self',
		aiselfcond = 'combatant.health < 20',
		aitargetcond = 'any',
		aipriority = 10,
	},
	debilitate = {
		name = 'Debilitate',
		code = 'debilitate',
		iconnorm = load("res://files/buttons/abils/Debilitate.png"),
		iconpressed = load("res://files/buttons/abils/Debilitate3.png"),
		icondisabled = load("res://files/buttons/abils/Debilitate2.png"),
		learnable = true,
		description = 'Light attack aimed to slow enemy down.',
		usetext = '$name goes for swift, maiming strike. ',
		target = 'one',
		targetgroup = 'enemy',
		effect = 'debilitateeffect',
		can_miss = true,
		learncost = 25,
		power = 0.65,
		cooldown = 2,
		type = 'physical',
		price = 100,
		costenergy = 0,
		costmana = 0,
		costother = '',
		attributes = ['damage', 'debuff'],
		reqs = {'level' : 1, 'sagi' : 1},
		aipatterns = ['attack'],
		aitargets = '1enemy',
		aiselfcond = 'any',
		aitargetcond = 'notineffect',
		aipriority = 3,
		castersfx = 'attackanimation',
	},
	deadlyblow = {
		name = 'Deadly Blow',
		code = 'deadlyblow',
		iconnorm = load("res://files/buttons/abils/Heavy Strike.png"),
		iconpressed = load("res://files/buttons/abils/Heavy Strike3.png"),
		icondisabled = load("res://files/buttons/abils/Heavy Strike2.png"),
		learnable = true,
		description = 'A deadly strike to destroy the enemy.',
		usetext = '$name goes for a deadly blow. ',
		target = 'one',
		targetgroup = 'enemy',
		can_miss = true,
		learncost = 35,
		power = 2,
		cooldown = 4,
		type = 'physical',
		price = 300,
		costenergy = 5,
		costmana = 0,
		costother = '',
		attributes = ['damage'],
		reqs = {'level' : 3, 'sstr' : 5, 'spec' : ["warrior", "assassin"]},
		aipatterns = ['attack'],
		aitargets = '1enemy',
		aiselfcond = 'any',
		aitargetcond = 'notineffect',
		aipriority = 4,
		castersfx = 'attackanimation',
	},
	protect = {
		name = 'Protect',
		code = 'protect',
		iconnorm = load("res://files/buttons/abils/Protect.png"),
		iconpressed = load("res://files/buttons/abils/Protect3.png"),
		icondisabled = load("res://files/buttons/abils/Protect2.png"),
		learnable = false,
		description = 'Shields target ally from incoming attacks. Takes less physical and energy damage from attacks. ',
		usetext = '$name moves in to protect $targetname. ',
		target = 'one',
		targetgroup = 'ally',
		effect = 'protecteffect',
		effectself = 'protectselfeffect',
		can_miss = true,
		power = 1,
		cooldown = 0,
		type = 'physical',
		price = 0,
		costenergy = 5,
		costmana = 0,
		costother = '',
		attributes = [],
		reqs = {level = 0},
		aipatterns = ['support'],
		aitargets = '1ally',
		aiselfcond = 'combatant.health > 50',
		aitargetcond = 'any',
		aipriority = 2,
	},
	heal = {
		name = 'Heal',
		code = 'heal',
		iconnorm = load("res://files/buttons/abils/Heal.png"),
		iconpressed = load("res://files/buttons/abils/Heal3.png"),
		icondisabled = load("res://files/buttons/abils/Heal2.png"),
		learnable = true,
		requiredspell = 'heal',
		description = 'Restores some health to the target. Requires mana to use. ',
		usetext = '$name supports $targetname with a [color=aqua]Healing Spell[/color]. ',
		target = 'one',
		targetgroup = 'ally',
		effect = null,
		can_miss = false,
		learncost = 25,
		power = 1,
		cooldown = 3,
		type = 'spell',
		price = 100,
		costenergy = 0,
		costmana = 10,
		costother = '',
		attributes = [],
		reqs = {'level' : 1, 'smaf' : 1},
		aipatterns = ['support'],
		aitargets = '1ally',
		aiselfcond = 'any',
		aitargetcond = 'target.health < 50',
		aipriority = 4,
	},
	sedation = {
		name = 'Sedation',
		code = 'sedation',
		iconnorm = load("res://files/buttons/abils/Sedation.png"),
		iconpressed = load("res://files/buttons/abils/Sedation3.png"),
		icondisabled = load("res://files/buttons/abils/Sedation2.png"),
		learnable = true,
		requiredspell = 'sedation',
		description = "Slows target's reaction, lowering its speed. ",
		usetext = '$name casts Sedation onto $targetname. ',
		target = 'one',
		targetgroup = 'enemy',
		effect = 'sedationeffect',
		can_miss = true,
		learncost = 40,
		power = 1,
		cooldown = 5,
		type = 'spell',
		price = 150,
		costenergy = 0,
		costmana = 10,
		costother = '',
		attributes = [],
		reqs = {'level' : 2, 'smaf' : 1},
		aipatterns = ['support'],
		aitargets = '1ally',
		aiselfcond = 'any',
		aitargetcond = 'target.health < 50',
		aipriority = 4,
	},
	barrier = {
		name = 'Barrier',
		code = 'barrier',
		iconnorm = load("res://files/buttons/abils/Barrier.png"),
		iconpressed = load("res://files/buttons/abils/Barrier3.png"),
		icondisabled = load("res://files/buttons/abils/Barrier2.png"),
		learnable = true,
		requiredspell = 'barrier',
		description = "Creates a magical barrier around target, raising its armor. ",
		usetext = '$name casts Barrier onto $targetname. ',
		target = 'one',
		targetgroup = 'ally',
		effect = 'barriereffect',
		can_miss = false,
		learncost = 35,
		power = 1,
		cooldown = 4,
		type = 'spell',
		price = 150,
		costenergy = 0,
		costmana = 12,
		costother = '',
		attributes = ['buff'],
		reqs = {'level' : 2, 'smaf' : 2},
		aipatterns = ['support'],
		aitargets = '1ally',
		aiselfcond = 'any',
		aitargetcond = 'any',
		aipriority = 3,
		targetsfx = 'barrieranimation',
	},
	shackle = {
		name = 'Shackle',
		code = 'shackle',
		iconnorm = load("res://files/buttons/abils/Shackle.png"),
		iconpressed = load("res://files/buttons/abils/Shackle3.png"),
		icondisabled = load("res://files/buttons/abils/Shackle2.png"),
		learnable = true,
		requiredspell = 'shackle',
		description = "Ties single target to ground making escape impossible. ",
		usetext = '$name casts Shackle onto $targetname. ',
		target = 'one',
		targetgroup = 'enemy',
		effect = 'shackleeffect',
		can_miss = false,
		learncost = 40,
		power = 0,
		cooldown = 5,
		type = 'spell',
		price = 150,
		costenergy = 0,
		costmana = 10,
		costother = '',
		attributes = ['debuff', 'noescape'],
		reqs = {'level' : 3, 'smaf' : 2},
		aipatterns = ['attack'],
		aitargets = '1enemy',
		aiselfcond = 'any',
		aitargetcond = 'any',
		aipriority = 5,
	},
	mindblast = {
		name = 'Mind Blast',
		code = 'mindblast',
		iconnorm = load("res://files/buttons/abils/Mindblast.png"),
		iconpressed = load("res://files/buttons/abils/Mindblast3.png"),
		icondisabled =load("res://files/buttons/abils/Mindblast2.png"),
		learnable = true,
		description = "Deals damage to single target enemy based on your Magic Affinity. ",
		usetext = '$name [color=aqua]uses Mind Blast[/color] at $targetname. ',
		target = 'one',
		targetgroup = 'enemy',
		effect = null,
		can_miss = true,
		learncost = 50,
		power = 1,
		cooldown = 3,
		type = 'spell',
		price = 100,
		costenergy = 0,
		costmana = 8,
		costother = '',
		attributes = ['damage'],
		reqs = {'level' : 2, 'smaf' : 1},
		aipatterns = ['attack'],
		aitargets = '1enemy',
		aiselfcond = 'any',
		aitargetcond = 'any',
		aipriority = 6,
	},
	acidspit = {
		name = 'Acid Spit',
		code = 'acidspit',
		learnable = true,
		iconnorm = load("res://files/buttons/abils/Acid spit.png"),
		iconpressed = load("res://files/buttons/abils/Acid spit3.png"),
		icondisabled = load("res://files/buttons/abils/Acid spit2.png"),
		description = "Deals damage to single target enemy and reduces its armor. Effect grows with Magic Affinity. ",
		usetext = '$name [color=aqua]Spits Acid[/color] at $targetname. ',
		target = 'one',
		targetgroup = 'enemy',
		effect = 'acidspiteffect',
		can_miss = true,
		learncost = 40,
		power = 2.5,
		cooldown = 4,
		type = 'spell',
		price = 200,
		costenergy = 0,
		costmana = 10,
		costother = '',
		attributes = ['damage','debuff'],
		reqs = {'level' : 4, 'smaf' : 4},
		aipatterns = ['attack'],
		aitargets = '1enemy',
		aiselfcond = 'any',
		aitargetcond = 'any',
		aipriority = 4,
	},
	heavystike = {
		name = 'Heavy Strike',
		code = 'heavystike',
		iconnorm = load("res://files/buttons/abils/Heavy Strike.png"),
		iconpressed = load("res://files/buttons/abils/Heavy Strike3.png"),
		icondisabled = load("res://files/buttons/abils/Heavy Strike2.png"),
		learnable = true,
		description = "A slow, yet powerful attack. Has a chance to Stun.",
		usetext = '$name goes for a powerful swing at $targetname. ',
		target = 'one',
		targetgroup = 'enemy',
		effect = null,
		script = 'stunchance',
		can_miss = true,
		learncost = 25,
		power = 1.75,
		cooldown = 3,
		type = 'physical',
		price = 250,
		costenergy = 0,
		costmana = 0,
		costother = '',
		attributes = ['damage'],
		reqs = {'level' : 3, 'sstr' : 2},
		aipatterns = ['attack'],
		aitargets = '1enemy',
		aiselfcond = 'any',
		aitargetcond = 'any',
		aipriority = 1,
		castersfx = 'attackanimation',
	},
	aimedstrike = {
		name = 'Aimed Strike',
		code = 'aimedstrike',
		iconnorm = load("res://files/buttons/abils/Aimed strike.png"),
		iconpressed = load("res://files/buttons/abils/Aimed strike3.png"),
		icondisabled = load("res://files/buttons/abils/Aimed strike2.png"),
		learnable = true,
		description = "Powerful, quick strike ignoring target's armor. ",
		usetext = '$name goes for an Aimed Strike at $targetname. ',
		target = 'one',
		targetgroup = 'enemy',
		effect = null,
		can_miss = true,
		learncost = 40,
		power = 1.5,
		cooldown = 4,
		type = 'physical',
		price = 250,
		costenergy = 0,
		costmana = 0,
		costother = '',
		attributes = ['damage','physpen'],
		reqs = {'level' : 2, 'sagi' : 2},
		aipatterns = ['attack'],
		aitargets = '1enemy',
		aiselfcond = 'any',
		aitargetcond = 'any',
		aipriority = 3,
		castersfx = 'attackanimation',
	},
	leechingstrike = {
		name = 'Leeching Strike',
		code = 'leechingstrike',
		iconnorm = load("res://files/buttons/abils/Lich strike.png"),
		iconpressed = load("res://files/buttons/abils/Lich strike3.png"),
		icondisabled = load("res://files/buttons/abils/Lich strike2.png"),
		learnable = true,
		description = "Mana infused attack which restores health based on dealt damage. ",
		usetext = '$name launches Leeching Strike at $targetname. ',
		target = 'one',
		targetgroup = 'enemy',
		effect = null,
		can_miss = true,
		learncost = 50,
		power = 1.2,
		cooldown = 4,
		type = 'physical',
		price = 300,
		costenergy = 0,
		costmana = 4,
		costother = '',
		attributes = ['damage', 'lifesteal'],
		reqs = {'level' : 4, 'sagi' : 3, 'smaf' : 2},
		aipatterns = ['attack'],
		aitargets = '1enemy',
		aiselfcond = 'any',
		aitargetcond = 'any',
		aipriority = 2,
		castersfx = 'attackanimation',
	},
	mindread = {
		name = 'Mind reading',
		code = 'mindread',
		iconnorm = load("res://files/buttons/abils/Mindread.png"),
		iconpressed = load("res://files/buttons/abils/Mindread3.png"),
		icondisabled = load("res://files/buttons/abils/Mindread2.png"),
		learnable = true,
		requiredspell = 'mindread',
		description = "A faster, combat oriented appliance of Mind Reading, allows you to get more information from your enemies. ",
		usetext = '$name cast Mind reading onto self. ',
		target = 'self',
		targetgroup = 'ally',
		effect = 'mindreadeffect',
		can_miss = false,
		learncost = 20,
		power = 0,
		cooldown = 3,
		type = 'physical',
		price = 100,
		costenergy = 0,
		costmana = 5,
		costother = '',
		attributes = ['buff', 'onlyself'],
		reqs = {},
		aitargets = 'self',
		aiselfcond = 'any',
		aitargetcond = 'any',
		aipriority = -1,
		targetsfx = 'mindreadanimation',
	},
	aoeattack = {
		name = 'Slam',
		code = 'aoeattack',
		iconnorm = load("res://files/buttons/abils/Attack.png"),
		iconpressed = load("res://files/buttons/abils/Attack2.png"),
		learnable = false,
		description = 'Attempts to attack chosen enemy.',
		usetext = '$name performs [color=aqua]Slam attack[/color]. ',
		target = 'all',
		targetgroup = 'enemy',
		effect = null,
		can_miss = true,
		power = 0.8,
		cooldown = 4,
		type = 'physical',
		price = 0,
		costenergy = 0,
		costmana = 0,
		costother = '',
		attributes = ['damage','allparty'],
		reqs = {level = 0},
		aipatterns = ['attack'],
		aitargets = 'enemies',
		aiselfcond = 'any',
		aitargetcond = 'any',
		aipriority = 100,
		castersfx = 'attackanimation',
		targetsfx = 'slamanimation',
	},
	dragonfirebreath = {
		name = 'Dragon Breath',
		code = 'dragonfirebreath',
		iconnorm = load("res://files/buttons/abils/Attack.png"),
		iconpressed = load("res://files/buttons/abils/Attack2.png"),
		learnable = false,
		description = 'Attempts to attack chosen enemy.',
		usetext = '$name uses [color=aqua]Dragon Breath[/color]. ',
		target = 'all',
		targetgroup = 'enemy',
		effect = 'firebreatheffect',
		can_miss = false,
		power = 0.4,
		cooldown = 6,
		type = 'spell',
		price = 0,
		costenergy = 0,
		costmana = 0,
		costother = '',
		attributes = ['damage','allparty','debuff'],
		reqs = {level = 0},
		aipatterns = ['attack'],
		aitargets = 'enemies',
		aiselfcond = 'any',
		aitargetcond = 'any',
		aipriority = 100,
		castersfx = 'firebreathanimationcaster',
		targetsfx = 'firebreathanimationtarget',
	},
	darknessattack = {
		name = 'Darkness Attack',
		code = 'darknessattack',
		iconnorm = load("res://files/buttons/abils/Attack.png"),
		iconpressed = load("res://files/buttons/abils/Attack2.png"),
		learnable = false,
		description = 'Attempts to attack chosen enemy.',
		usetext = '$name uses [color=aqua]Drain[/color]. ',
		target = 'all',
		targetgroup = 'enemy',
		effect = 'darknesscurseeffect',
		can_miss = false,
		power = 1,
		cooldown = 4,
		type = 'spell',
		price = 0,
		costenergy = 0,
		costmana = 0,
		costother = '',
		attributes = ['damage','allparty','debuff'],
		reqs = {level = 0},
		aipatterns = ['attack'],
		aitargets = 'enemies',
		aiselfcond = 'any',
		aitargetcond = 'any',
		aipriority = 100,
		castersfx = 'firebreathanimationcaster',
		targetsfx = 'firebreathanimationtarget',
	},
	alwayshitattack = {
		name = 'Precise Attack',
		code = 'alwayshitattack',
		iconnorm = load("res://files/buttons/abils/Attack.png"),
		iconpressed = load("res://files/buttons/abils/Attack2.png"),
		learnable = false,
		description = 'Attempts to attack chosen enemy.',
		usetext = '$name uses [color=aqua]Precise attack[/color] landing on $targetname. ',
		target = 'one',
		targetgroup = 'enemy',
		effect = null,
		can_miss = false,
		power = 1.2,
		cooldown = 5,
		type = 'physical',
		price = 0,
		costenergy = 0,
		costmana = 0,
		costother = '',
		attributes = ['damage'],
		reqs = {level = 0},
		aipatterns = ['attack'],
		aitargets = '1enemy',
		aiselfcond = 'any',
		aitargetcond = 'any',
		aipriority = 5,
		castersfx = 'attackanimation',
	},
	stunattack = {
		name = 'Stun',
		code = 'stunattack',
		iconnorm = null,
		iconpressed = null,
		learnable = false,
		description = 'Attempts to attack chosen enemy.',
		usetext = '$name launches [color=aqua]Stun attack[/color] at $targetname. ',
		target = 'one',
		targetgroup = 'enemy',
		effect = 'stun',
		can_miss = true,
		power = 1,
		cooldown = 6,
		type = 'physical',
		price = 0,
		costenergy = 0,
		costmana = 0,
		costother = '',
		attributes = ['damage'],
		reqs = {level = 0},
		aipatterns = ['attack'],
		aitargets = '1enemy',
		aiselfcond = 'any',
		aitargetcond = 'any',
		aipriority = 5,
		castersfx = 'attackanimation',
	},
	webattack = {
		name = 'Shoot Web',
		code = 'webattack',
		iconnorm = null,
		iconpressed = null,
		learnable = false,
		description = 'Attempts to attack chosen enemy.',
		usetext = '$name [color=aqua]shoots web[/color] at $targetname. ',
		target = 'one',
		targetgroup = 'enemy',
		effect = 'enemyslow',
		can_miss = true,
		learncost = 20,
		power = 1,
		accuracy = 0.8,
		cooldown = 4,
		type = 'physical',
		price = 0,
		costenergy = 0,
		costmana = 0,
		costother = '',
		attributes = ['damage'],
		reqs = {'level' : 1, 'race' : 'Arachna'},
		aipatterns = ['attack'],
		aitargets = '1enemy',
		aiselfcond = 'any',
		aitargetcond = 'any',
		aipriority = 3,
		castersfx = 'attackanimation',
	},
	masshealcouncil = {
		name = 'Mass Heal',
		code = 'masshealcouncil',
		iconnorm = null,
		iconpressed = null,
		learnable = false,
		description = 'Attempts to attack chosen enemy.',
		usetext = '$name [color=aqua]casts mass heal[/color]. ',
		target = 'all',
		targetgroup = 'ally',
		effect = null,
		can_miss = false,
		power = 1,
		accuracy = 1,
		cooldown = 4,
		type = 'spell',
		price = 0,
		costenergy = 0,
		costmana = 0,
		costother = '',
		attributes = [],
		reqs = {level = 0},
		aipatterns = ['support'],
		aitargets = 'allies',
		aiselfcond = 'any',
		aitargetcond = 'any',
		aipriority = 2,
	},
	###---Added by Expansion---###
	npcweakwebattack = {
		name = 'Shoot Weak Web',
		code = 'npcweakwebattack',
		iconnorm = load("res://files/buttons/abils/Attack.png"),
		iconpressed = load("res://files/buttons/abils/Attack3.png"),
		icondisabled = load("res://files/buttons/abils/Attack2.png"),
		learnable = false,
		description = 'Attempts to attack chosen enemy.',
		usetext = '$name turns around and [color=aqua]sprays $his web[/color] at all enemies trying to cover the battlefield in $his sticky webs. ',
		target = 'all',
		targetgroup = 'enemy',
		effect = 'enemyslow',
		can_miss = true,
		power = 0.5,
		accuracy = 0.5,
		cooldown = 5,
		type = 'physical',
		price = 0,
		costenergy = 0,
		costmana = 0,
		costother = '',
		attributes = ['damage','debuff'],
		reqs = {'level' : 0, 'race' : 'Arachna'},
		aipatterns = ['attack'],
		aitargets = 'enemies',
		aiselfcond = 'any',
		aitargetcond = 'any',
		aipriority = 3,
		castersfx = 'attackanimation',
	},
	takeaim = {
		name = 'Take Aim',
		code = 'takeaim',
		iconnorm = globals.loadimage(globals.modfolder + "/Leo/Images/bullseyeblue.png"),
		iconpressed = globals.loadimage(globals.modfolder + "/Leo/Images/bullseyered.png"),
		icondisabled = globals.loadimage(globals.modfolder + "/Leo/Images/bullseyeblack.png"),
		learnable = false,
		description = 'Take aim for a better attack next turn. ',
		logtext = '[name1][color=aqua] takes aim [/color]. ',
		target = 'self',
		targetgroup = 'ally',
		effect = 'takeaimeffect',
		effectself = 'takeaimeffect',
		can_miss = false,
		power = 1,
		cooldown = 3,
		type = 'physical',
		price = 0,
		costenergy = 0,
		costmana = 0,
		costother = '',
		attributes = [],
		reqs = {level = 0},
		aipatterns = ['attack'],
		aitargets = 'self',
		aipriority = 2,
	},
	drainheat = {
		name = 'Drain Heat',
		code = 'drainheat',
		iconnorm = null,
		iconpressed = null,
		learnable = false,
		description = 'Drains the heat from the air.',
		logtext = '[name1] turns the air [color=aqua]freezing cold [/color]. ',
		target = 'all',
		targetgroup = 'enemy',
		effect = 'frozeneffect',
		can_miss = false,
		power = 1.23,
		cooldown = 3,
		type = 'spell',
		price = 0,
		costenergy = 0,
		costmana = 0,
		costother = '',
		attributes = ['damage','allparty','debuff'],
		reqs = {level = 0},
		aipatterns = ['attack'],
		aitargets = 'enemies',
		aipriority = 3,
		castersfx = 'attackanimation',
	},
	dragunder = {
		name = 'Drag Under',
		code = 'dragunder',
		iconnorm = null,
		iconpressed = null,
		learnable = false,
		description = 'Drags the target under the surface.',
		logtext = '[name1][color=aqua] drags [/color][targetname1] under the surface. ',
		target = 'one',
		targetgroup = 'enemy',
		effect = 'trappedeffect',
		can_miss = true,
		power = 0.5,
		cooldown = 2,
		type = 'physical',
		price = 0,
		costenergy = 0,
		costmana = 0,
		costother = '',
		attributes = ['damage','debuff'],
		reqs = {level = 0},
		aipatterns = ['attack'],
		aitargets = '1enemy',
		aipriority = 3,
		castersfx = 'attackanimation',
		script = 'initiatetrapped'
	},
	devour = {
		name = 'Devour',
		code = 'devour',
		iconnorm = null,
		iconpressed = null,
		learnable = false,
		description = 'Devours a trapped enemy.',
		logtext = '[name1][color=aqua] devours [/color][targetname1]. ',
		target = 'one',
		targetgroup = 'enemy',
		effect = null,
		effectself = 'surfaceprotectioneffect',
		can_miss = true,
		power = 1.25,
		cooldown = 0,
		type = 'physical',
		price = 0,
		costenergy = 0,
		costmana = 0,
		costother = '',
		attributes = ['damage'],
		reqs = {level = 0},
		aipatterns = ['attack'],
		aitargets = '1enemy',
		aipriority = 4,
		castersfx = 'attackanimation',
	},
	rescue = {
		name = 'Rescue',
		code = 'rescue',
		iconnorm = globals.loadimage(globals.modfolder + "/Leo/Images/under.png"),
		iconpressed = globals.loadimage(globals.modfolder + "/Leo/Images/underred.png"),
		icondisabled = globals.loadimage(globals.modfolder + "/Leo/Images/underdark.png"),
		learnable = false,
		description = 'Rescue a trapped ally.',
		logtext = '[name1][color=aqua] helps [/color][targetname1] to get free. ',
		target = 'one',
		targetgroup = 'ally',
		effect = null,
		can_miss = true,
		power = 0,
		cooldown = 1,
		type = 'physical',
		price = 0,
		costenergy = 20,
		costmana = 0,
		costother = '',
		attributes = [],
		reqs = {level = 0},
		aipatterns = ['support'],
		aitargets = '1ally',
		aipriority = 1,
		script = 'rescue'
	},
	poisonstrike = {
		name = 'Posion strike',
		code = 'poisonstrike',
		iconnorm = null,
		iconpressed = null,
		learnable = false,
		description = 'Attack using posion.',
		logtext = '[name1] makes a[color=aqua] poisonous strike [/color]at [targetname1]. ',
		target = 'one',
		targetgroup = 'enemy',
		effect = 'poisoneffect',
		can_miss = true,
		power = 0.75,
		cooldown = 2,
		type = 'physical',
		costenergy = 0,
		costmana = 0,
		costother = '',
		attributes = ['damage', 'debuff'],
		reqs = {level = 0},
		aipatterns = ['attack'],
		aitargets = '1enemy',
		aipriority = 3,
		castersfx = 'attackanimation',
		script = 'inflictpoison'
	},
	spew = {
		name = 'Spew the guts',
		code = 'spew',
		iconnorm = null,
		iconpressed = null,
		learnable = false,
		description = 'Belch out bad water at an enemy.',
		logtext = '[name1][color=aqua] spews [/color]watery bile over [targetname1] and recovers. ',
		target = 'one',
		targetgroup = 'enemy',
		effect = null,
		can_miss = false,
		power = 0.5,
		cooldown = 5,
		type = 'physical',
		costenergy = 0,
		costmana = 0,
		costother = '',
		attributes = ['damage', 'debuff'],
		reqs = {level = 0},
		aipatterns = ['attack'],
		aitargets = '1enemy',
		aipriority = 2,
		castersfx = 'attackanimation',
		script = 'spewbile'
	},
	rush = {
		name = 'Sudden Rush',
		code = 'rush',
		iconnorm = null,
		iconpressed = null,
		learnable = false,
		description = 'Rush at an enemy and attack.',
		logtext = '[name1][color=aqua] rushes  towards [/color][targetname1] with a sudden attack. ',
		target = 'one',
		targetgroup = 'enemy',
		effect = null,
		can_miss = true,
		power = 1.0,
		cooldown = 3,
		accuracy = 1.2,
		type = 'physical',
		costenergy = 0,
		costmana = 0,
		costother = '',
		attributes = ['damage'],
		reqs = {level = 0},
		aipatterns = ['attack'],
		aitargets = '1enemy',
		aipriority = 2,
		castersfx = 'attackanimation',
	},
	burningblades = {
		name = 'Burning Blades',
		code = 'burningblades',
		iconnorm = globals.loadimage(globals.modfolder + "/Leo/Images/burningblade.png"),
		iconpressed = globals.loadimage(globals.modfolder + "/Leo/Images/burningbladeoff.png"),
		icondisabled = globals.loadimage(globals.modfolder + "/Leo/Images/burningbladeoff.png"),
		learnable = false,
		description = 'Metal should burn.',
		logtext = '[name1] casts[color=aqua] burning blades[/color]. ',
		target = 'all',
		targetgroup = 'ally',
		effect = 'burningbladeeffect',
		can_miss = false,
		power = 0.01,
		accuracy = 1,
		cooldown = 5,
		type = 'spell',
		price = 0,
		costenergy = 0,
		costmana = 10,
		costother = '',
		attributes = ['damage'],
		reqs = {level = 0},
		aipatterns = ['support'],
		aitargets = 'allies',
		aiselfcond = 'any',
		aitargetcond = 'any',
		aipriority = 2,
	}

	###---End Expansion---###
}

#warning-ignore:unused_class_variable
var effects = {
	protecteffect = {
		icon = load("res://files/buttons/abils/Protect.png"),
		duration = 1,
		name = 'Protected',
		description = 'This character is being covered from direct hits',
		code = 'protecteffect',
		effect = 'protecttarget',
		type = 'buff',
		stats = [],
	},
	protectselfeffect = {
		icon = load("res://files/buttons/mainscreen/48.png"),
		duration = 1,
		name = 'Protector',
		description = 'Reduces received damage.',
		code = 'protectselfeffect',
		effect = 'protectself',
		type = 'buff',
		stats = [],
	},
	escapeeffect = {
		icon = load("res://files/buttons/abils/Escape.png"),
		duration = 1,
		name = 'Escape',
		description = 'Escapes combat on next turn.',
		code = 'escapeeffect',
		effect = 'escapeeffect',
		type = 'buff',
		stats = [],
	},
	healeffect = {
		icon = load("res://files/buttons/abils/Heal.png"),
		duration = 0,
		effect = 'restorehealth',
		type = 'buff',
	},
	sedationeffect = {
		icon = load("res://files/buttons/abils/Sedation.png"),
		duration = 3,
		name = 'Sedation',
		code = 'sedationeffect',
		type = 'debuff',
		stats = [['speed', '-(3+,caster.magic,)']],
	},
	barriereffect = {
		icon = load("res://files/buttons/abils/Barrier.png"),
		duration = 3,
		name = 'Barrier',
		code = 'barriereffect',
		type = 'buff',
		stats = [['armor', '3+,caster.magic,*3']],
	},
	debilitateeffect = {
		icon = load('res://files/buttons/abils/Debilitate.png'),
		duration = 3,
		name = 'Debilitate',
		code = 'debilitateeffect',
		type = 'debuff',
		stats = [['speed', '-(2+,caster.attack,/3)']],
	},
	mindreadeffect = {
		icon = load('res://files/buttons/abils/Mindread.png'),
		duration = 5,
		name = 'Mind Reading',
		code = 'mindreadeffect',
		type = 'buff',
		stats = [],
	},
	shackleeffect = {
		icon = load("res://files/buttons/abils/Shackle.png"),
		duration = 6,
		name = "Shackled",
		code = 'shackleeffect',
		type = 'debuff',
		stats = [],
	},
	acidspiteffect = {
		icon = load("res://files/buttons/abils/Acid spit.png"),
		duration = 5,
		name = "Acid",
		code = 'acidspiteffect',
		type = 'debuff',
		stats = [['armor', '-(3+,caster.magic,)']],
	},
	firebreatheffect = {
		icon = load("res://files/buttons/combat/fire.png"),
		duration = 2,
		name = "On Fire",
		code = 'firebreatheffect',
		type = 'onendturn',
		description = "Target is taking damage every turn",
		script = 'firebreathdamage',
		stats = [],
	},
	darknesscurseeffect = {
		icon = load("res://files/buttons/abils/Acid spit.png"),
		duration = 4,
		name = "Drained",
		code = 'darknesscurseeffect',
		type = 'script',
		description = "",
		script = 'darknesscurse',
		stats = [],
	},
	curseeffectatk = {
		icon = load("res://files/buttons/combat/curse1.png"),
		duration = 5,
		name = "Drained",
		code = 'curseeffectatk',
		type = 'debuff',
		description = "Attack is drastically reduced.",
		stats = [['attack', '-(25, )']],
	},
	curseeffectmgc = {
		icon = load("res://files/buttons/combat/curse2.png"),
		duration = 5,
		name = "Drained",
		code = 'curseeffectmgc',
		type = 'debuff',
		description = "Magic is drastically reduced.",
		stats = [['magic', '-(6, )']],
	},
	enemyslow = {
		icon = load("res://files/buttons/abils/Sedation.png"),
		duration = 3,
		name = "Slow",
		code = 'enemyslow',
		type = 'debuff',
		stats = [['speed', '-(5, )']],
	},
	stun = {
		icon = load("res://files/buttons/abils/Heavy Strike.png"),
		duration = 1,
		name = "Stunned",
		code = 'stun',
		type = 'debuff',
		description = "This character can't act this turn.",
		stats = [],
	},
	lustweak = {
		icon = load("res://files/buttons/sex.png"),
		duration = -1,
		name = "Horny",
		code = 'lustweak',
		type = 'passive',
		stats = [['speed', '-(3,)']],
	},
	luststrong = {
		icon = load("res://files/buttons/sexdown.png"),
		duration = -1,
		name = "Very Horny",
		code = 'luststrong',
		type = 'passive',
		stats = [['speed', '-(5,)'],['attack','-(3,)']],
	},
	exhaust = {
		icon = load("res://files/buttons/exhaust.png"),
		duration = -1,
		name = "Exhausted",
		code = 'exhaust',
		type = 'passive',
		description = 'This character suffers from exhaustion and they deal less damage\n[color=yellow]-33% damage[/color]',
		stats = [],
	},
	pregnancy = {
		icon = load("res://files/buttons/abils/pregnant.png"),
		duration = -1,
		name = "Pregnant",
		code = 'pregnancy',
		description = '-25% Speed',
		type = 'passive',
		stats = [],
	},
	#BBP- Added Combat Effects (Stolen from Leo)
	aciddamageeffect = {
		icon = load("res://files/buttons/abils/Acid spit.png"),
		duration = 5,
		name = "Acid Damage",
		code = 'aciddamageeffect',
		description = "Target is taking damage every turn",
		type = 'onendturn',
		script = 'applyaciddamage',
		stats = [],
	},
	panic = {
		icon = globals.loadimage(globals.modfolder + "/Leo/Images/panic.png"),
		duration = -1,
		name = "Panic",
		code = 'panic',
		type = 'passive',
		description = 'This character has panicked.',
		stats = [['speed', '-(5, )']],
	},
	takeaimeffect = {
		icon = globals.loadimage(globals.modfolder + "/Leo/Images/bullseyeblue.png"),
		duration = 2,
		name = 'Take Aim',
		code = 'takeaimeffect',
		type = 'buff',
		description = null, #stats will be added to tooltip automatically
		stats = [['speed', '5'], ['attack', '8']],
	},
	firststrikeeffect = {
		icon = globals.loadimage(globals.modfolder + "/Leo/Images/firststrike.png"),
		duration = 1,
		name = 'First Strike',
		code = 'firststrikeeffect',
		type = 'buff',
		description = null, #stats will be added to tooltip[ automatically
		stats = [['speed', '3'], ['attack', '3']],
	},
	monsterescapeeffect = {
		icon = globals.loadimage(globals.modfolder + "/Leo/Images/wildescape.png"),
		duration = 1,
		name = "Monster Escape",
		code = 'monsterescapeeffect',
		type = 'buff',
		description = "Target is hidden in swirling mists",
		stats = [['protection', '25']],
	},
	frozeneffect = {
		icon = globals.loadimage(globals.modfolder + "/Leo/Images/snow.png"),
		duration = 2,
		name = "Frozen",
		code = 'frozeneffect',
		description = "Cold enough to freeze",
		type = 'onendturn',
		script = 'applyfreeze',
		stats = [],
	},
	trappedeffect = {
		icon = globals.loadimage(globals.modfolder + "/Leo/Images/under.png"),
		duration = 9,
		name = "Trapped",
		code = 'trappedeffect',
		description = "Trapped",
		type = 'buff',
		stats = [['speed', '-10'], ['attack', '-7']],
	},
	surfaceprotectioneffect = {
		icon = load("res://files/buttons/mainscreen/48.png"),
		duration = 1,
		name = "Underneath",
		code = 'surfaceprotectioneffect',
		type = 'buff',
		description = "Target is partly hidden beneath the surface",
		stats = [['protection', '25']],
	},
	poisoneffect = {
		icon = globals.loadimage(globals.modfolder + "/Leo/Images/poison.png"),
		duration = 3,
		name = "Poison",
		code = 'poisoneffect',
		description = "Target is poisoned and takes extra damage when health drops",
		type = 'onendturn',
		script = 'applypoison',
		stats = [],
	},
	burningbladeeffect = {
		icon = globals.loadimage(globals.modfolder + "/Leo/Images/burningblade.png"),
		duration = 4,
		name = "Burning Blades",
		code = 'burningbladeeffect',
		description = "This weapon is burning",
		type = 'buff',
		stats = [['attack', '+8']],
		script = 'applyburningblades',
	}
#BBP- End of Leo Effects

}

func restorehealth(caster, target):
	var text = ''
	var value = 25 + (caster.magic*9)
	target.hp += max(value, 10)
	text = '$name restores ' + str(value) + ' health.'
	return text

func damage(combatant, value):
	combatant.attack += value

func armor(combatant, value):
	combatant.armor += value

func speed(combatant, value):
	combatant.speed += value

func passive(combatant, value):
	combatant.passives.append(value)

func protection(combatant, value):
	combatant.protection += value

#warning-ignore:unused_argument
func lust(combatant, value):
	combatant.lust += 2

#warning-ignore:unused_class_variable
var passivesdict = {
	doubleattack15 = {code = 'doubleattack15', effect = 'doubleattack', effectvalue = 15, descript = '15% chance to attack twice'},
	doubleattack25 = {code = 'doubleattack25', effect = 'doubleattack', effectvalue = 25, descript = '25% chance to attack twice'},
	doubleattack50 = {code = 'doubleattack50', effect = 'doubleattack', effectvalue = 50, descript = '50% chance to attack twice'},
	cultleaderpassive = {code = 'cultleaderpassive', effect = 'cultleaderpassive', effectvalue = null, descript = 'Grows stronger when allies defeated'}
}

func stunchance(caster, target, basechance = 25):
	var chance = basechance
	if caster.person != null:
		chance = caster.person.sstr*8
	if target.faction == 'boss':
		chance = chance/4
	if chance >= rand_range(0,100):
		caster.scene.sendbuff(caster, target, 'stun')
		target.actionpoints = 0

func firebreathdamage(target):
	var value = 6
	target.hp -= value
	var text = '$name burns for [color=red]' + str(value) + '[/color] damage.'
	return target.person.dictionary(text)

func darknesscurse(target):
	target.scene.removebuff("darknesscurseeffect",target)
	if randf() >= 0.5:
		target.scene.sendbuff(target,target,"curseeffectatk")
	else:
		target.scene.sendbuff(target,target,"curseeffectmgc")

# BBP - More functions stolen from Leo
#incombat (combat preparation)
func powerful(combatant, value):
	combatant.attack += combatant.person.sstr - value

func acceleration(combatant, value):
	combatant.speed += combatant.person.sstr - value

func firststrike(combatant, value):
	combatant.scene.sendbuff(combatant, combatant, 'firststrikeeffect')

func addability(combatant, value):
	if !combatant.activeabilities.has(value):
		combatant.activeabilities.append(value)
		
func takeaim(combatant, value): #Leo for legacy bows only
	addability(combatant, 'takeaim')
	
#ability use
func aciddamage(caster, target): #Leo The armour reduction is applied as the acid strike debuff, so another method needed for the acid damage over time.
	var turns = caster.magic/2
	if globals.state.spec == 'Mage' && caster.group == 'player':
		turns *= 1.2
	caster.scene.sendbuff(caster, target, 'aciddamageeffect')
	target.effects[effects.aciddamageeffect.code].duration = ceil(turns)
	if target.effects[effects.aciddamageeffect.code].caster.group == 'player':
		target.effects[effects.aciddamageeffect.code].caster = target #Leo script abilities only called for 'enemy' caster group

func inflictpoison(caster, target):
	var neweffect = target.effects.poisoneffect
	neweffect.tracker = target.hp

func initiateflanking(caster, target):
	caster.scene.removebuff('flankeffect', caster)
	if target.effects.has('packeffect'):
		caster.scene.sendbuff(caster, caster, 'flankeffect')
		caster.effects['flankeffect'].victim = target
	else:
		target.scene.sendbuff(caster, target, 'packeffect')
	
func initiatetrapped(caster, target): #Leo assume target is in the player group
	for i in target.scene.playergroup:
		addability(i, 'rescue')
	target.cooldowns['rescue'] = 3
	
func rescue(caster, target):
	if target.effects.has('trappedeffect'):
		target.scene.removebuff('trappedeffect', target)

func spewbile(caster, target):
	caster.hp += 20
	caster.scene.sendbuff(caster, target, 'sedationeffect')
	target.effects[effects.sedationeffect.code].duration = 1

#effects (enemy turn)
#reminder of enemyturn() order : playergroup autoattacks, process effects of both playerggroup and enemygroup, enemy attacks, enemygroup cooldowns, playergroup cooldowns, end of combat checks
func applyaciddamage(target):
	var value = 20
	if target.person != null && target.person.traits.has("Sturdy"):
		value = value*0.85

	target.hp -= value
	return '[name1] suffers [color=green]' + str(value) + '[/color] acid damage.'

func applyfreeze(target):
	if target.passives.has('coldresist'):
		return '[name1] is protected from the cold'
	elif randi() % 3 == 0:
		target.scene.sendbuff(target, target, 'stun')
		return '[name1] is frozen'

	return '[name1] endures the cold'

func applypoison(target):
	var text = ' '
	var currenteffect = target.effects.poisoneffect
	var healthchange = target.hp - currenteffect.tracker
	if healthchange > 0:
		currenteffect.duration = 1
		text = '[name1] is cured of posion'
	elif healthchange < 0:
		var damage = 10
		if target.person != null && target.person.traits.has("Sturdy"):
			damage = damage*0.85
		target.hp -= damage
		currenteffect.duration += 2
		text = 'The poison inside [name1] gets worse'
	else:
		text = '[name1] endures the posion'
	currenteffect.tracker = target.hp
	return text
	
