extends Node


var enemygrouppools = {
	#ralphD
	noenemyencountered = {
		units = [['wolf',1,1]], awareness = -10, captured = null, special = 'noenemyencountered',
		description = 'You should not see [color=aqua]this[/color].',
		descriptionambush = '',
	},
	#/ralphD
	treasurechest = {
		units = [['wolf',1,1]], awareness = -10, captured = null, special = 'treasurechest',
		description = 'You find a small [color=aqua]treasure chest[/color].',
		descriptionambush = '',
	},
	blockedsection = {
		units = [['wolf',1,1]], awareness = -10, captured = null, special = 'blockedsection',
		description = 'You find a small [color=aqua]treasure chest[/color].',
		descriptionambush = '',
	},
	wolveseasy = {
		units = [['wolf',2,3]], awareness = 6, captured = null, special = null,
		description = 'You come across a [color=aqua]small pack of wolves[/color].',
		descriptionambush = 'You are attacked by a [color=aqua]small pack of wolves[/color].',
	},
	direwolveseasy = {
		units = [['direwolf',2,5]], awareness = 18, captured = null, special = null,
		description = 'You come across a pack of [color=aqua]dangerous dire wolves[/color].',
		descriptionambush = 'You are attacked by a pack of [color=aqua]dangerous dire wolves[/color].',
	},
	wolveswithperson = {
		units = [['wolf',4,8]], awareness = -10, captured = ['thugvictim'], special = null,
		description = 'You come across a [color=aqua]group of wolves[/color] attacking a lost [color=yellow]$capturedrace[/color].',
		descriptionambush = 'You are attacked by a [color=aqua]small pack of wolves[/color].',
	},
	wolveshard = {
		units = [['wolf',3,6]], awareness = 15, captured = null, special = null,
		description = 'You come across a [color=aqua]large pack of wolves[/color].',
		descriptionambush = 'You are attacked by a [color=aqua]large pack of wolves[/color].',
	},
	solobear = {
		units = [['bear',1,1]], awareness = 6, captured = null, special = null,
		description = "$scoutname spots a [color=aqua]brown bear[/color] several yards away, just in time to let you react to him. ",
		descriptionambush =  "As you walk through the wilderness, you hear a fierce roar. It seems you provoked a [color=aqua]bear[/color] by getting into its territory. It breaks out of the woodwork and goes for an attack.",
	},
	plantseasy = {
		units = [['plant',2,3]], awareness = -10, captured = null, special = null,
		description = 'You come across a bunch of [color=aqua]hostile, animated plants[/color]. ',
	},
	plantswithperson = {
		units = [['plant',3,6]], awareness = -10, captured = ['thugvictim'], special = null,
		description = 'You spot a bunch of frenzied, [color=aqua]man-eating plants[/color] seizing a [color=yellow]$capturedrace $capturedchild[/color]. ',
	},
	fewcougars = {
		units = [['cougar',2,3]], awareness = 10, captured = null, special = null,
		description = "$scoutname spots a group of [color=aqua]mountain cougars[/color] searching for prey. ",
		descriptionambush =  "You are being attacked by a group of [color=aqua]mountain cougars[/color]!",
	},
	solospider = {
		units = [['spider',1,1]], awareness = 12, captured = null, special = null,
		description = "$scoutname spots a [color=aqua]giant spider hiding[/color] in the shadows. ",
		descriptionambush =  "A [color=aqua]horse-sized spider[/color] has detected you trespassing its domain and jumps out to attack.",
	},
	spidergroup = {
		units = [['spider',3,4]], awareness = 24, captured = null, special = null,
		description = "$scoutname spots a [color=aqua]group of giant spiders[/color] hiding in the shadows. ",
		descriptionambush =  "You are attacked by a [color=aqua]group of giant spiders[/color].",
	},
	oozesgroup = {
		units = [['ooze',2,3]], awareness = -10, captured = null, special = null,
		description = "You come across a [color=aqua]group of ooze monsters[/color]. ",
	},
	banditseasy = {
		units = [['bandit',2,3]], awareness = 6, captured = null, special = null,
		description = 'You spot a [color=aqua]small group of stray bandits[/color]. They seem to be unaware of your presence as of yet. ',
		descriptionambush = 'You are attacked by a [color=aqua]small group of stray bandits[/color]. ',
	},
	thugseasy = {
		units = [['bandit',2,2]], awareness = -10, captured = ['thugvictim'], special = null,
		description = 'You come across a [color=aqua]pair of thugs[/color] bullying a [color=yellow]bystander[/color]. They are busy right now, so you could pass them by unnoticed... ',
	},
	banditsmedium = {
		units = [['banditleader', 0,1],['bandit',3,6]], awareness = 12, captured = null, special = null,
		description = 'You spot a [color=aqua]medium-sized group of stray bandits[/color]. They seem to be unaware of your presence as of yet. ',
		descriptionambush = 'You are attacked by a [color=aqua]group of stray bandits[/color]. ',
	},
	banditshard = {
		units = [['banditleader', 1,1],['bandit',7,8]], awareness = 15, captured = null, special = null,
		description = 'You spot a [color=aqua]large group of stray bandits[/color]. They seem to be unaware of your presence as of yet. ',
		descriptionambush = 'You are attacked by a [color=aqua]large group of stray bandits[/color]. ',
	},
	CaliBossSlaver = {
		units = [['slaver',1,1]], awareness = -10, captured = null, special = null,
		description = 'You spot a [color=aqua]small group of stray bandits[/color]. They seem to be unaware of your presence as of yet. ',
		descriptionambush = 'You are attacked by a [color=aqua]small group of stray bandits[/color]. ',
	},
	CaliStrayBandit = {
		units = [['bandit',1,1]], awareness = -10, captured = null, special = null,
		description = 'You spot a [color=aqua]small group of stray bandits[/color]. They seem to be unaware of your presence as of yet. ',
		descriptionambush = 'You are attacked by a [color=aqua]small group of stray bandits[/color]. ',
	},
	banditcamp = {
		units = [['bandit',6,8],['banditleader', 1,2]], awareness = -10, captured = ['banditcampcaptured', 'banditcampcaptured'], special = null,
		description = 'You come across a [color=aqua]bandit encampment[/color]. You can spot numerous watchmen moving around and a few captives too, which are likely to be sold for slaves soon. ',
	},
	elfguards = {
		units = [['elfguard',2,3]], awareness = 15, captured = null, special = null,
		description = "You spot a local [color=aqua]patrol of elven warriors[/color] scouting the surroundings. Surely, they won't be happy with trespassers as this is elven territory. ", #Removed Tribal to avoid confusion
		descriptionambush = 'You are attacked by a [color=aqua]small group of elven warriors[/color]. ',
	},
	lizardfolkpatrol = {
		units = [['lizardfolkwarrior',2,4]], awareness = 15, captured = null, special = null,
		description = "You spot a local [color=aqua]patrol of lizardfolk warriors[/color] surverying the marsh. They are very territorial, your transgression won't be appreciated. ",
		descriptionambush = 'You are attacked by a [color=aqua]small group of lizardfolk warriors[/color]. ',
	},
	fairy = {
		units = [['fairy',1,1]], awareness = -10, captured = null, special = null,
		description = 'You spot a lone [color=aqua]wild fairy $child[/color] floating through the woods. ',
	},
	fairyfew = {
		units = [['fairy',2,4]], awareness = -10, captured = null, special = null, escape = 7,
		description = 'You spot a [color=aqua]small group of wild fairies[/color] playing around. ',
		descriptionescape = "A group of wild fairies escapes from you before you get close to them. ",
	},
	#ralphA
	fairyattackers = {
		units = [['fairy2',2,3]], awareness = -10, captured = ['thugvictim'], special = null,
		description = 'You spot a [color=aqua]small group of wild fairies[/color] swarming menacingly around a [color=yellow]lost traveler[/color]. They seem thoroughly entertained. You could leave this poor soul to be molested...',
	},
	seraph1 = {
		units = [['seraph1',1,1]], awareness = -10, captured = null, special = null,
		description = 'You spot a lost [color=aqua]Seraph[/color] wandering in a daze, perhaps too tired to fly home. ',
	},
	harpyattackers = {
		units = [['harpy1',3,5]], awareness = -10, captured = ['seraphvictim'], special = null,
		description = 'You spot a [color=aqua]small flight of harpies[/color] harassing a [color=yellow]lone Seraph[/color] in flight. They seem intent on grounding and violating their prey. Your eyes meet briefly with those of the seemingly innocent victim.',
	},
	centaurattackers = {
		units = [['centaur1',2,5]], awareness = -10, captured = ['thugvictim'], special = null,
		description = 'You spot some [color=aqua]Centaur outriders[/color] circling a [color=yellow]lone traveler[/color] who must have strayed too close to their camp. The Centaurs appear unlikely to let the traveler off with a warning. You could intervene, but it will get ugly.',
	},
	centaur1 = {
		units = [['centaur1',1,1]], awareness = -10, captured = null, special = null,
		description = 'You spot a lone [color=aqua]Centaur outcast[/color] trotting aimlessly. You are upwind and as yet unseen.',
	},
	arachnaweb = {
		units = [['arachna1',1,1],['spider',2,5]], awareness = -10, captured = ['webvictim'], special = null,
		description = 'You freeze in your tracks and turn to see [color=aqua]Giant Spiders led by a wild Arachna[/color] spinning a [color=yellow]large cocoon[/color] containing some wayward traveler entangled in their webs. You could attack the humungous arachnids, but they will not give up their prize without a fight.',
	},
	delfvsgob1 = {
		units = [['darkelf1',2,3],['goblin',3,7]], awareness = 20, captured = null, special = null,
		description = 'You come upon [color=aqua]dark elves and goblins skirmishing[/color]. They seem intent on killing one another and are unaware of your presence as of yet. ',
		descriptionambush = 'You walk right into the middle of a [color=aqua]pitched battle between goblins and dark elves[/color]. Despite their animosity toward one another, they must have some sort of pact because they charge at you together.',
	},
	delfattackers1 = {
		units = [['darkelf1',2,3]], awareness = -10, captured = ['goblinvictim'], special = null,
		description = 'You hear the ring of steel on steel and follow it to find [color=aqua]dark elves[/color] circling a [color=yellow]lone goblin survivor[/color] surrounded by the bodies of its peers. One of the dark elves prepares a finishing blow.',
	},
	delfattackers2 = {
		units = [['darkelf1',2,4],['cougarmount',3,7]], awareness = 40, captured = null, special = null,
		description = 'You spot a [color=aqua]group of dark elf guards[/color] patrolling the tunnels mounted on [color=aqua]massive cougars[/color]. You remain hidden for the moment.',
		descriptionambush = "A [color=aqua]group of dark elf guards[/color] takes your party by surprise, barreling through the caves at you while mounted on [color=aqua]massive cougars[/color]. You are not certain when you strayed into their territory, but these dark elves will not tolerate your invasion.",
	},
	delffew = {
		units = [['darkelf1',2,4]], awareness = -10, captured = null, special = null, escape = 50,
		description = 'You spot a [color=aqua]small group of dark elves[/color] walking through the caves. ',
		descriptionescape = "A group of dark elves escapes from you before you can get close to them. How many more have been watching you from the darkness?",
	},
	goblinattackers1 = {
		units = [['goblin',3,6],['ooze',3,6]], awareness = 30, captured = null, special = null,
		description = 'You smell the [color=aqua]filthy cave goblins[/color] before you see them. They appear to be watching over a [color=aqua]quivering mass of oozes[/color]. You remain hidden for the moment.',
		descriptionambush = "A [color=aqua]group of goblins[/color] ambushes and harries you right into a [color=aqua]mass of oozes[/color]. The goblins have prepared a lethal trap, and you've fallen right into it.",
	},
	goblinattackers2 = {
		units = [['goblin',3,6]], awareness = -10, captured = ['delfvictim'], special = null,
		description = 'You come upon a [color=aqua]group of slavering goblins[/color] cackling and looking down upon a prone [color=yellow]young dark elf[/color] who must have strayed too close to goblin territory. It is unclear whether they intend to rape or devour their victim.',
	},
	#/ralphA
	goblingroup = {
		units = [['goblin',3,7]], awareness = 9, captured = null, special = null,
		description = 'You spot a [color=aqua]group of cave goblins[/color] moving through the tunnels. ',
		descriptionambush = "A [color=aqua]group of cave goblins[/color] jumps on you. ",
	},
	dryad = {
		units = [['dryad',1,1]], awareness = -10, captured = null, special = null,
		description = 'You spot a wild [color=aqua]$race $child[/color] walking through the woods.',
	},
	dryad2 = { #ralph4
		units = [['dryad2',2,4]], awareness = 20, captured = null, special = null, #ralph4
		description = 'You spot a group of bark-armored dryads apparently searching the woods for intruders.', #ralph4
		descriptionambush = 'You are attacked by [color=aqua]wild defenders of the forest[/color]. ', #ralph4
	},
	nereidgroup = { #ralph4
		units = [['nereidgroup',2,6]], awareness = 30, captured = null, special = null, #ralph4
		description = 'You spot a small group of Nereid scouts armed and armored primarily with coral.', #ralph4
		descriptionambush = 'You are attacked by [color=aqua]Nereid Skirmishers[/color] attempting to secure the beachhead for their kind. ', #ralph4
	}, #ralph4
	monstergirl = {
		units = [['monstergirl',1,1]], awareness = -10, captured = null, special = null, escape = 6, #ralph4
		description =  "You come across a rare [color=aqua]$race monster $child[/color]. $He hasn't spotted you yet. ",
		descriptionambush = 'You are attacked by a frenzied [color=aqua]$race $child[/color] in search of mate. ', #ralph4
		descriptionescape = "A wild $race escapes from you before you get close to $him. ",
	},
	monstergirlfew = {
		units = [['monstergirl',2,4]], awareness = -10, captured = null, special = null, escape = 12,
		description =  "You spot a [color=aqua]small group of wild $race[/color] playing around.  ",
		descriptionescape = "A group of [color=aqua]wild $race[/color] escapes from you before you get close to them. ",
	},
	harpy = {
		units = [['harpy',1,1]], awareness = -10, captured = null, special = null,
		description =  "You come across a [color=aqua]$race monster $child[/color]. $He hasn't spotted you yet. ",
	},
	slaverseasy = {
		units = [['slaver',2,3]], awareness = -10, captured = ['slavervictim'], special = 'slaversenc',
		description = "You spot a group of [color=aqua]$unitnumber slavers[/color] leading a [color=yellow]sole victim[/color]. You can't make out any more details without getting closer.",
	},
	slaversmedium = {
		units = [['slaver',3,5]], awareness = -10, captured = ['slavervictim', 'slavervictim'], special = 'slaversenc',
		description = "You spot a group of [color=aqua]$unitnumber slavers[/color] leading a few recently [color=yellow]captured victims[/color]. You can't say much about them without getting closer.",
	},
	peasant = {
		units = [['peasant',1,1]], awareness = -10, captured = null, special = null,
		description = "You meet a lone [color=aqua]$race $child[/color], native to these lands. $He seems to be unaware of your presence as of yet. ",
	},
	peasantgroup = {
		units = [['peasant',2,3]], awareness = -10, captured = null, special = null,
		description = "You meet a group of [color=aqua]$unitnumber strangers[/color], native to these lands. They seem to be unaware of your presence as of yet. ",
	},
	travelersgroup = {
		units = [['traveller',2,3]], awareness = -10, captured = null, special = null,
		description = "You meet a group of [color=aqua]$unitnumber travellers[/color] moving by on the road. They seem to be unaware of your presence as of yet. ",
	},
	troglodytesmall = {
		units = [['troglodyte',3,5]], awareness = 20, captured = null, special = null,
		description = 'You spot a [color=aqua]small group of troglodytes[/color]. They seem to be unaware of your presence as of yet. ',
		descriptionambush = 'You are attacked by a [color=aqua]small group of troglodytes[/color]. ',
	},
	troglodytelarge = {
		units = [['troglodyte',7,10]], awareness = 16, captured = null, special = null,
		description = 'You spot a [color=aqua]large group of troglodytes[/color]. They seem to be unaware of your presence as of yet. ',
		descriptionambush = 'You are attacked by a [color=aqua]large group of troglodytes[/color]. ',
	},
	mutant = {
		units = [['mutant',1,1]], awareness = 25, captured = null, special = null,
		description = 'You spot an [color=aqua]ugly creature[/color], deformed by magical energy.',
		descriptionambush = 'You are attacked by a [color=aqua]mutant[/color]. ',
	},
	gembeetle = {
		units = [['gembeetle',1,1]], awareness = -10, captured = null, special = null,
		description = "You spot an unusual creature. A shiny, [color=aqua]multicolored bug[/color] of significant size. ",
	},
	bossgolem = {
		units = [['bossgolem',1,1]], awareness = -10, captured = null, special = null,
		description = "Golem Boss",
	},
	bosswyvern = {
		units = [['bosswyvern',1,1]], awareness = -10, captured = null, special = null,
		description = "Wyvern Boss",
	},
	dragonwhelps = {
		units = [['dragonwhelp',2,6]], awareness = 40, captured = null, special = null,
		description = 'You discover a pieces of crumbled eggshells, signaling about [color=aqua]hatched dragons[/color] nearby. ',
		descriptionambush = 'You are attacked by a group of [color=aqua]dragon whelps[/color]. ',
	},
	hardbeasts = {
		units = [['hardbeast',1,4]], awareness = 30, captured = null, special = null,
		description = 'You spot a numerous fresh tracks belonging to some [color=aqua]heavy animals[/color]. ',
		descriptionambush = 'You are attacked by a group of [color=aqua]hardened beasts[/color]. ',
	},
	possessed = {
		units = [['possessed',2,6]], awareness = 25, captured = null, special = null,
		description = 'You spot a group of [color=aqua]possessed people[/color] ahead of you. ',
		descriptionambush = 'You are attacked by a group of [color=aqua]Possessed[/color]. ',
	},
	cultists = {
		units = [['cultist',2,6]], awareness = 40, captured = null, special = null,
		description = 'You spot a group of [color=aqua]cultists[/color] ahead of you.',
		descriptionambush = 'You are attacked by a group of [color=aqua]cultists[/color]. ',
	},
	cultists2 = {
		units = [['cultist',1,3], ['possessed', 1, 3]], awareness = 40, captured = null, special = null,
		description = 'You spot a group of [color=aqua]cultists and possessed[/color] ahead of you.',
		descriptionambush = 'You are attacked by a group of [color=aqua]cultists and possessed[/color]. ',
	},
	giantcrab = {
		units = [['giantcrab',1,1]], awareness = 40, captured = null, special = null,
		description = 'You spot a giant crab lurking around',
		descriptionambush = 'You are attacked by a [color=aqua]giant crab[/color]. ',
	},
	giantcrabs = {
		units = [['giantcrab',2,3]], awareness = 30, captured = null, special = null,
		description = 'You spot a small group of giant crabs',
		descriptionambush = 'You are attacked by a group of [color=aqua]giant crabs[/color]. ',
	},
	shadows = {
		units = [['shadow',2,6]], awareness = 35, captured = null, special = null,
		description = 'You spot a mass of shadows ahead of you.',
		descriptionambush = 'You are attacked by an intangible [color=aqua]shadows[/color]. ',
	},
	cultistswithperson = {
		units = [['cultist',3,6]], awareness = -10, captured = ['banditcampcaptured'], special = null,
		description = 'You spot a group of cultists, harshly abusing a single person. Thankfully, they seem to not notice you yet. ',
	},
	possesedwithdragonkin = {
		units = [['possessed',3,6]], awareness = -10, captured = ['dragonkincaptured'], special = null,
		description = 'You spot a group of possessed, guarding a rebellious dragonkin. Thankfully, they seem to not notice you yet. ',
	},
	bossdragon = {
		units = [['bossdragon',1,1]], awareness = -10, captured = null, special = null,
		description = "Dragon Boss",
	},
	bosscultist = {
		units = [['cultist',1,1],['cultboss',1,1],['cultist',1,1]], awareness = -10, captured = null, special = null,
		description = "Cultist Leader",
	},
	finalboss = {
		units = [['finalboss',1,1]], awareness = -10, captured = null, special = null,
		description = "",
	},
	bookmutants = {
		units = [['mutant',3,3]], awareness = 25, captured = null, special = null,
		description = 'Group of mutants',
	},
	tishaquestenemy = {
		units = [['banditleader',1,1],['bandit',3,3]], awareness = -10, captured = null, special = null,
		description = "",
	},
	ivranquestenemy = {
		units = [['ivran',1,1],['elfguard',4,4]], awareness = -10, captured = null, special = null,
		description = "",
	},
	ayneris1 = {
		units = [['ayneris',1,1],['elfguard',3,3]], awareness = -10, captured = null, special = null,
		description = "",
	},
	ayneris2 = {
		units = [['ayneris',1,1],['elfguard',7,7]], awareness = -10, captured = null, special = null,
		description = "",
	},
	frostforddryadquest = {
		units = [['direwolf',6,6],['plant',4,4]], awareness = -10, captured = null, special = null,
		description = "",
	},
	frostfordzoequest = {
		units = [['marauder',9,9]], awareness = -10, captured = null, special = null,
		description = "",
	},
	finaleelves = {
		units = [['elfguard',7,7],['elfleader',3,3]], awareness = -10, captured = null, special = null,
		description = "",
	},
	finaleslavers = {
		units = [['marauder',8,8],['marauderleader',2,2]], awareness = -10, captured = null, special = null,
		description = "",
	},
	finaledavid = {
		units = [['david',1,1],['investigator',4,4]], awareness = -10, captured = null, special = null,
		description = "",
	},
	finalegarthor = {
		units = [['garthor',1,1],['orcwarrior',7,7]], awareness = -10, captured = null, special = null,
		description = "",
	},
	finalehade = {
		units = [['hademerc',3,3],['hade',1,1],['hademerc',3,3]], awareness = -10, captured = null, special = null,
		description = "",
	},
	finalecouncil = {
		units = [['orderprotector',4,4],['councilboss',1,1],['orderprotector',4,4]], awareness = -10, captured = null, special = null,
		description = "",
	},
	wimbornguards = {
		units = [['wimbornpatrol',3,4]], awareness = -10, captured = null, special = null,
		description = "You have been spotted by a [color=aqua]patrolling militia[/color] group from Wimborn.\nIt seems they are inclined to take you to task despite your station. ", #ralph4 - added 2nd line
	},
	wimbornguardsmany = {
		units = [['wimbornpatrol',7,10]], awareness = -10, captured = null, special = null,
		description = "You have been spotted by a [color=aqua]large patrolling militia[/color] group from Wimborn.\nIt seems they are inclined to take you to task despite your station. ", #ralph4 - added 2nd line
	},
	gornguards = {
		units = [['gornpatrol',3,4]], awareness = -10, captured = null, special = null,
		description = "You have been spotted by a [color=aqua]patrolling militia[/color] group from Gorn.\nIt seems they are inclined to take you to task despite your station. ", #ralph4 - added 2nd line
	},
	gornguardsmany = {
		units = [['gornpatrol',7,10]], awareness = -10, captured = null, special = null,
		description = "You have been spotted by a [color=aqua]large patrolling militia[/color] group from Gorn.\nIt seems they are inclined to take you to task despite your station. ", #ralph4 - added 2nd line
	},
	frostfordguards = {
		units = [['frostfordpatrol',3,4]], awareness = -10, captured = null, special = null,
		description = "You have been spotted by a [color=aqua]patrolling militia[/color] group from Frostford.\nIt seems they are inclined to take you to task despite your station. ", #ralph4 - added 2nd line
	},
	frostfordguardsmany = {
		units = [['frostfordpatrol',7,10]], awareness = -10, captured = null, special = null,
		description = "You have been spotted by a [color=aqua]large patrolling militia[/color] group from Frostford.\nIt seems they are inclined to take you to task despite your station. ", #ralph4 - added 2nd line
	},
	amberguardguards = {
		units = [['amberguardpatrol',3,4]], awareness = -10, captured = null, special = null,
		description = "You have been spotted by a [color=aqua]patrolling militia[/color] group from Amberguard. ",
	},
	amberguardguardsmany = {
		units = [['amberguardpatrol',7,10]], awareness = -10, captured = null, special = null,
		description = "You have been spotted by a [color=aqua]large patrolling militia[/color] group from Amberguard. ",
	},
}

var capturespool = {
	thugvictim = {
		capturerace = ['area'],
		captureoriginspool = [{value = 'rich', weight = 1},{value = 'commoner', weight = 3},{value = 'poor', weight = 6},{value = 'slave', weight = 12}],
		captureagepool = [{value = 'child', weight = 1},{value = 'teen', weight = 3}, {value = 'adult', weight = 2}],
		capturesex = ['any'],
		faction = 'stranger',
	},
	#ralphA
	seraphvictim = {
		capturerace = [['Seraph',1]],
		captureoriginspool = [{value = 'rich', weight = 10},{value = 'commoner', weight = 30},{value = 'poor', weight = 60},{value = 'slave', weight = 1}],
		captureagepool = [{value = 'child', weight = 1},{value = 'teen', weight = 5}, {value = 'adult', weight = 4}],
		capturesex = ['any'],
		faction = 'stranger',
	},
	webvictim = {
		capturerace = ['any'],
		captureoriginspool = [{value = 'noble', weight = 2},{value = 'rich', weight = 3},{value = 'commoner', weight = 5},{value = 'poor', weight = 3},{value = 'slave', weight = 1}],
		captureagepool = [{value = 'child', weight = 1},{value = 'teen', weight = 1}, {value = 'adult', weight = 2}],
		capturesex = ['any'],
		faction = 'stranger',
	},
	goblinvictim = {
		capturerace = [['Goblin',1]],
		captureoriginspool = [{value = 'poor', weight = 1},{value = 'slave', weight = 1}],
		captureagepool = [{value = 'child', weight = 2},{value = 'teen', weight = 5}, {value = 'adult', weight = 4}],
		capturesex = ['any'],
		faction = 'stranger',
	},
	delfvictim = {
		capturerace = [['Dark Elf',1]],
		captureoriginspool = [{value = 'poor', weight = 2},{value = 'commoner', weight = 1}],
		captureagepool = [{value = 'child', weight = 2},{value = 'teen', weight = 1}],
		capturesex = ['any'],
		faction = 'stranger',
	},
	#/ralphA
	slavervictim = {
		capturerace = ['area'],
		captureoriginspool = [{value = 'rich', weight = 2},{value = 'commoner', weight = 5},{value = 'poor', weight = 5},{value = 'slave', weight = 12}],
		captureagepool = [['child',20],['teen',60], ['adult', 100]],
		capturesex = ['any'],
		faction = 'stranger',
	},
	banditcampcaptured = {
		capturerace = ['any'],
		captureoriginspool = [{value = 'noble', weight = 2},{value = 'rich', weight = 5},{value = 'commoner', weight = 8},{value = 'poor', weight = 10}],
		captureagepool = [{value = 'child', weight = 2},{value = 'teen', weight = 3}, {value = 'adult', weight = 3}],
		capturesex = ['any'],
		faction = 'stranger',
	},
	dragonkincaptured = {
		capturerace = [['Dragonkin',1]],
		captureoriginspool = [{value = 'noble', weight = 2},{value = 'rich', weight = 5},{value = 'commoner', weight = 8}],
		captureagepool = [{value = 'child', weight = 3},{value = 'teen', weight = 3}, {value = 'adult', weight = 1}],
		capturesex = ['any'],
		faction = 'stranger',
	},
}


var enemypool = {
	wolf = {
		name = 'Wolf',
		code = 'wolf',
		faction = 'animal',
		icon = load("res://files/images/enemies/wolf.png"),
		special = null,
		capture = null,
		level = 2,
		rewardpool = {bestialessenceing = 25},
		rewardgold = 0,
		rewardexp = 10,
		stats = {health = 25, power = 12, speed = 12, energy = 50, armor = 0, magic = 0, abilities = ['attack']},
		skills = [],
	},
	direwolf = {
		name = 'Dire Wolf',
		code = 'direwolf',
		faction = 'animal',
		icon = load("res://files/images/enemies/wolf.png"),
		special = null,
		level = 4,
		capture = null,
		rewardpool = {bestialessenceing = 40},
		rewardgold = 0,
		rewardexp = 20,
		stats = {health = 50, power = 20, speed = 15, energy = 50, armor = 1, magic = 0, abilities = ['attack'], passives = ['doubleattack25']},
		skills = [],
	},
	plant = {
		name = 'Plant',
		code = 'plant',
		level = 3,
		faction = 'plant',
		icon = load("res://files/images/enemies/plant.png"),
		special = null,
		capture = null,
		rewardpool = {natureessenceing = 30},
		rewardgold = 0,
		rewardexp = 15,
		stats = {health = 40, power = 12, speed = 12, energy = 50, armor = 3, magic = 0, abilities = ['attack']},
		skills = [],
	},
	ooze = {
		name = 'Ooze',
		code = 'ooze',
		level = 6,
		faction = 'animal',
		icon = load("res://files/images/enemies/slime.png"),
		special = null,
		capture = null,
		rewardpool = {taintedessenceing = 25, fluidsubstanceing = 20},
		rewardgold = 0,
		rewardexp = 25,
		stats = {health = 75, power = 16, speed = 15, energy = 50, armor = 15, magic = 0, abilities = ['attack']},
		skills = [],
	},
	bear = {
		name = 'Bear',
		code = 'bear',
		faction = 'animal',
		icon = load("res://files/images/enemies/bear.png"),
		special = null,
		capture = null,
		rewardpool = {bestialessenceing = 50},
		rewardgold = 0,
		rewardexp = 20,
		level = 7,
		stats = {health = 90, power = 20, speed = 18, energy = 50, armor = 3, magic = 0, abilities = ['attack']},
		skills = [],
	},
	cougar = {
		name = 'Cougar',
		code = 'cougar',
		faction = 'animal',
		icon = load("res://files/images/enemies/cougar.png"),
		special = null,
		capture = null,
		level = 4,
		rewardpool = {bestialessenceing = 35},
		rewardgold = 0,
		rewardexp = 20,
		stats = {health = 60, power = 13, speed = 20, energy = 50, armor = 1, magic = 0, abilities = ['attack'], passives = ['doubleattack15']},
		skills = [],
	},
	cougarmount = {
		name = 'Cougar',
		code = 'cougar',
		faction = 'animal',
		icon = load("res://files/images/enemies/cougar.png"),
		special = null,
		capture = null,
		level = 8,
		rewardpool = {bestialessenceing = 35},
		rewardgold = 0,
		rewardexp = 20,
		stats = {health = 90, power = 25, speed = 30, energy = 50, armor = 2, magic = 0, abilities = ['attack'], passives = ['doubleattack15']},
		skills = [],
	},
	spider = {
		name = 'Giant Spider',
		code = 'spider',
		faction = 'animal',
		icon = load("res://files/images/enemies/spider.png"),
		special = null,
		capture = null,
		rewardpool = {bestialessenceing = 75},
		level = 12,
		rewardgold = 0,
		rewardexp = 50,
		stats = {health = 120, power = 25, speed = 18, energy = 50, armor = 5, magic = 2, abilities = ['attack','webattack']},
		skills = [],
	},
	peasant = {
		name = 'Lone Stranger',
		code = 'peasant',
		faction = 'stranger',
		icon = load("res://files/images/enemies/stranger.png"),
		special = null,
		capture = true,
		capturerace = ['area'],
		captureoriginspool = [{value = 'rich', weight = 1},{value = 'commoner', weight = 5},{value = 'poor', weight = 20}],
		captureagepool = [{value = 'child', weight = 1},{value = 'teen', weight = 3}, {value = 'adult', weight = 4}],
		capturesex = ['any'],
		rewardpool = {gold = 15, supply = 25},
		rewardgold = [1,5],
		rewardexp = 15,
		stats = {health = 40, power = 4, speed = 15, energy = 50, armor = 2, magic = 1, abilities = ['attack']},
		gear = 'peasant',
		skills = [],
	},
	elfguard = {
		name = 'An Elf Warrior',
		code = 'elfguard',
		faction = 'elf',
		icon = load("res://files/images/enemies/elfguard.png"),
		special = null,
		capture = true,
		capturerace = ['amberguard'],
		captureoriginspool = [{value = 'rich', weight = 2},{value = 'commoner', weight = 6},{value = 'poor', weight = 10}],
		captureagepool = [{value = 'teen', weight = 2}, {value = 'adult', weight = 4}],
		capturesex = ['any'],
		rewardpool = {gold = 20, supply = 35},
		rewardgold = [1,5],
		rewardexp = 30,
		stats = {health = 75, power = 8, speed = 20, energy = 50, armor = 3, magic = 2, abilities = ['attack']},
		gear = 'elfs',
		skills = [],
	},
	elfleader = {
		name = 'An Elf Leader',
		code = 'elfleader',
		faction = 'elf',
		icon = load("res://files/images/enemies/elfguard.png"),
		special = null,
		capture = true,
		capturerace = ['amberguard'],
		captureoriginspool = [{value = 'rich', weight = 2},{value = 'commoner', weight = 6},{value = 'poor', weight = 10}],
		captureagepool = [{value = 'teen', weight = 2}, {value = 'adult', weight = 4}],
		capturesex = ['any'],
		rewardpool = {gold = 20, supply = 35},
		rewardgold = [1,5],
		rewardexp = 30,
		stats = {health = 125, power = 13, speed = 24, energy = 50, armor = 6, magic = 2, abilities = ['attack']},
		gear = 'elfs',
		skills = [],
	},

	orcwarrior = {
		name = 'An Orc Warrior',
		code = 'orcwarrior',
		faction = 'gorn',
		icon = load("res://files/images/enemies/orcguard.png"),
		special = null,
		capture = true,
		capturerace = ['area'],
		captureoriginspool = [{value = 'rich', weight = 2},{value = 'commoner', weight = 6},{value = 'poor', weight = 10}],
		captureagepool = [{value = 'teen', weight = 2}, {value = 'adult', weight = 4}],
		capturesex = ['any'],
		rewardpool = {gold = 20, supply = 35},
		rewardgold = [1,5],
		rewardexp = 30,
		stats = {health = 90, power = 11, speed = 23, energy = 50, armor = 5, magic = 2, abilities = ['attack']},
		gear = 'guard',
		skills = [],
	},
	lizardfolkwarrior = {
		name = 'Warrior',
		code = 'lizardfolkwarrior',
		capturerace = [['Lizardfolk',100]],
		faction = 'monster',
		icon = load("res://files/aric_expansion_images/enemies/swamplizardm_enemy.png"),
		special = null,
		capture = true,
		captureoriginspool = [{value = 'rich', weight = 1},{value = 'commoner', weight = 4},{value = 'poor', weight = 10}],
		captureagepool = [{value = 'teen', weight = 2}, {value = 'adult', weight = 6}],
		capturesex = ['any'],
		rewardpool = {gold = 20, supply = 35},
		rewardgold = [1,5],
		rewardexp = 35,
		stats = {health = 85, power = 10, speed = 18, energy = 50, armor = 6, magic = 0, abilities = ['attack']},
		gear = 'marsh',
		skills = [],
	},
	investigator = {
		name = 'Investigator',
		code = 'investigator',
		faction = 'gorn',
		icon = load("res://files/images/enemies/humanguard.png"),
		special = null,
		capture = true,
		capturerace = ['area'],
		captureoriginspool = [{value = 'rich', weight = 2},{value = 'commoner', weight = 6},{value = 'poor', weight = 10}],
		captureagepool = [{value = 'teen', weight = 2}, {value = 'adult', weight = 4}],
		capturesex = ['any'],
		rewardpool = {gold = 20, supply = 35},
		rewardgold = [1,5],
		rewardexp = 30,
		stats = {health = 125, power = 14, speed = 28, energy = 50, armor = 4, magic = 2, abilities = ['attack']},
		gear = 'guard',
		skills = [],
	},
	orderprotector = {
		name = "Order's Protector",
		code = 'orderprotector',
		faction = 'gorn',
		icon = load("res://files/images/enemies/humanguard.png"),
		special = null,
		capture = true,
		capturerace = ['area'],
		captureoriginspool = [{value = 'rich', weight = 2},{value = 'commoner', weight = 6},{value = 'poor', weight = 10}],
		captureagepool = [{value = 'teen', weight = 2}, {value = 'adult', weight = 4}],
		capturesex = ['any'],
		rewardpool = {gold = 20, supply = 35},
		rewardgold = [1,5],
		rewardexp = 30,
		stats = {health = 110, power = 12, speed = 22, energy = 50, armor = 8, magic = 2, abilities = ['attack']},
		gear = 'guard',
		skills = [],
	},
	garthor = {
		name = 'Garthor',
		code = 'garthor',
		faction = 'gorn',
		icon = load("res://files/images/enemies/garthor.png"),
		special = null,
		capture = true,
		capturerace = ['area'],
		captureoriginspool = [{value = 'rich', weight = 2},{value = 'commoner', weight = 6},{value = 'poor', weight = 10}],
		captureagepool = [{value = 'teen', weight = 2}, {value = 'adult', weight = 4}],
		capturesex = ['any'],
		rewardpool = {gold = 20, supply = 35},
		rewardgold = [1,5],
		rewardexp = 30,
		stats = {health = 250, power = 15, speed = 29, energy = 50, armor = 6, magic = 2, abilities = ['attack']},
		gear = 'guard',
		skills = [],
	},
	david = {
		name = 'David',
		code = 'david',
		faction = 'gorn',
		icon = load("res://files/images/enemies/humanguard.png"),
		special = null,
		capture = true,
		capturerace = ['area'],
		captureoriginspool = [{value = 'rich', weight = 2},{value = 'commoner', weight = 6},{value = 'poor', weight = 10}],
		captureagepool = [{value = 'teen', weight = 2}, {value = 'adult', weight = 4}],
		capturesex = ['any'],
		rewardpool = {gold = 20, supply = 35},
		rewardgold = [1,5],
		rewardexp = 30,
		stats = {health = 200, power = 18, speed = 35, energy = 50, armor = 5, magic = 2, abilities = ['attack']},
		gear = 'guard',
		skills = [],
	},
	hade = {
		name = 'Hade',
		code = 'hade',
		faction = 'bandit',
		icon = load("res://files/images/enemies/hade.png"),
		special = null,
		capture = true,
		capturerace = ['area'],
		captureoriginspool = [{value = 'rich', weight = 2},{value = 'commoner', weight = 6},{value = 'poor', weight = 10}],
		captureagepool = [{value = 'teen', weight = 2}, {value = 'adult', weight = 4}],
		capturesex = ['any'],
		rewardpool = {gold = 20, supply = 35},
		rewardgold = [1,5],
		rewardexp = 30,
		stats = {health = 400, power = 60, speed = 35, energy = 50, armor = 12, magic = 5, abilities = ['attack','alwayshitattack']},
		gear = 'guard',
		skills = [],
	},
	hademerc = {
		name = "Hade's Associate",
		code = 'hademerc',
		faction = 'bandit',
		icon = load("res://files/images/enemies/banditleaderm.png"),
		iconalt = load("res://files/images/enemies/banditleaderf.png"),
		special = null,
		capture = true,
		capturerace = ['area'],
		captureoriginspool = [{value = 'rich', weight = 2},{value = 'commoner', weight = 6},{value = 'poor', weight = 10}],
		captureagepool = [{value = 'teen', weight = 2}, {value = 'adult', weight = 4}],
		capturesex = ['any'],
		rewardpool = {gold = 20, supply = 35},
		rewardgold = [1,5],
		rewardexp = 30,
		stats = {health = 125, power = 25, speed = 30, energy = 50, armor = 6, magic = 2, abilities = ['attack']},
		gear = 'guard',
		skills = [],
	},
	councilboss = {
		name = "Council leader",
		code = 'councilboss',
		faction = 'bandit',
		icon = null,
		special = null,
		capture = true,
		capturerace = ['area'],
		captureoriginspool = [{value = 'rich', weight = 2},{value = 'commoner', weight = 6},{value = 'poor', weight = 10}],
		captureagepool = [{value = 'teen', weight = 2}, {value = 'adult', weight = 4}],
		capturesex = ['any'],
		rewardpool = {gold = 20, supply = 35},
		rewardgold = [1,5],
		rewardexp = 30,
		stats = {health = 240, power = 50, speed = 30, energy = 50, armor = 9, magic = 2, abilities = ['attack','masshealcouncil']},
		gear = 'guard',
		skills = [],
	},
	fairy = {
		name = 'Fairy',
		code = 'fairy',
		faction = 'monster',
		icon = load("res://files/images/enemies/fairym.png"),
		iconalt = load("res://files/images/enemies/fairyf.png"),
		special = '',
		capture = true,
		capturerace = [['Fairy',100]],
		captureoriginspool = [{value = 'commoner', weight = 1},{value = 'poor', weight = 3}],
		captureagepool = [{value = 'child', weight = 1},{value = 'teen', weight = 3}, {value = 'adult', weight = 2}],
		capturesex = ['any'],
		rewardpool = {magicessenceing = 55},
		rewardgold = [5,10],
		rewardexp = 20,
		stats = {health = 65, power = 10, speed = 18, energy = 50, armor = 0, magic = 5, abilities = ['attack']},
		gear = 'forest',
		skills = [],
	},
	goblin = {
		name = 'Goblin',
		code = 'goblin',
		faction = 'monster',
		icon = null,
		special = '',
		capture = true,
		capturerace = [['Goblin',100]],
		captureoriginspool = [{value = 'commoner', weight = 1},{value = 'poor', weight = 3}],
		captureagepool = [{value = 'child', weight = 1},{value = 'teen', weight = 3}, {value = 'adult', weight = 3}],
		capturesex = ['any'],
		rewardpool = {gold = 55},
		rewardgold = [5,10],
		rewardexp = 15,
		stats = {health = 60, power = 8, speed = 21, energy = 50, armor = 1, magic = 2, abilities = ['attack']},
		gear = 'weakbandits',
		skills = [],
	},
	harpy = {
		name = 'Harpy',
		code = 'harpy',
		faction = 'monster',
		icon = null,
		special = '',
		capture = true,
		capturerace = [['Harpy',100]],
		captureoriginspool = [{value = 'commoner', weight = 1},{value = 'poor', weight = 2}],
		captureagepool = [{value = 'child', weight = 1},{value = 'teen', weight = 3}, {value = 'adult', weight = 3}],
		capturesex = ['any'],
		rewardpool = {bestialessenceing = 35},
		rewardgold = [5,10],
		rewardexp = 20,
		stats = {health = 75, power = 6, speed = 22, energy = 50, armor = 1, magic = 0, abilities = ['attack']},
		gear = 'weakbandits',
		skills = [],
	},
	dryad = {
		name = 'Dryad',
		code = 'dryad',
		faction = 'monster',
		icon = load("res://files/images/enemies/dryadm.png"),
		iconalt = load("res://files/images/enemies/dryadf.png"),
		special = '',
		capture = true,
		capturerace = [['Dryad',100]],
		captureoriginspool = [{value = 'commoner', weight = 1},{value = 'poor', weight = 1}],
		captureagepool = [{value = 'child', weight = 1},{value = 'teen', weight = 3}, {value = 'adult', weight = 4}],
		capturesex = ['any'],
		rewardpool = {natureessenceing = 35},
		rewardgold = [5,10],
		rewardexp = 20,
		stats = {health = 75, power = 6, speed = 15, energy = 50, armor = 0, magic = 0, abilities = ['attack']},
		gear = 'forest',
		skills = [],
	},
	#ralphA
	fairy2 = {
		name = 'Fairy',
		code = 'fairy2',
		faction = 'monster',
		icon = load("res://files/images/enemies/fairym.png"),
		iconalt = load("res://files/images/enemies/fairyf.png"),
		special = '',
		capture = true,
		capturerace = [['Fairy',100]],
		captureoriginspool = [{value = 'commoner', weight = 1},{value = 'poor', weight = 3}],
		captureagepool = [{value = 'child', weight = 1},{value = 'teen', weight = 3}, {value = 'adult', weight = 4}],
		capturesex = ['any'],
		rewardpool = {magicessenceing = 55},
		rewardgold = [5,10],
		rewardexp = 20,
		stats = {health = 65, power = 10, speed = 35, energy = 50, armor = 0, magic = 5, abilities = ['attack']},
		gear = 'forest',
		skills = [],
	},
	seraph1 = {
		name = 'Seraph',
		code = 'seraph1',
		faction = 'monster',
		icon = load("res://files/images/enemies/stranger.png"),
		iconalt = load("res://files/images/enemies/stranger.png"),
		special = '',
		capture = true,
		capturerace = [['Seraph',100]],
		captureoriginspool = [{value = 'commoner', weight = 1},{value = 'poor', weight = 1}],
		captureagepool = [{value = 'child', weight = 8},{value = 'teen', weight = 6}, {value = 'adult', weight = 1}],
		capturesex = ['any'],
		rewardpool = {gold = 10},
		rewardgold = [5,20],
		rewardexp = 20,
		stats = {health = 65, power = 6, speed = 18, energy = 50, armor = 2, magic = 0, abilities = ['attack']},
		gear = 'peasant',
		skills = [],
	},
	harpy1 = {
		name = 'Harpy',
		code = 'harpy1',
		faction = 'monster',
		icon = load("res://files/images/enemies/stranger.png"),
		iconalt = load("res://files/images/enemies/stranger.png"),
		special = '',
		capture = true,
		capturerace = [['Harpy',100]],
		captureoriginspool = [{value = 'slave', weight = 1},{value = 'poor', weight = 1}],
		captureagepool = [{value = 'child', weight = 1},{value = 'teen', weight = 2}, {value = 'adult', weight = 3}],
		capturesex = ['any'],
		rewardpool = {gold = 10},
		rewardgold = [5,20],
		rewardexp = 20,
		stats = {health = 65, power = 6, speed = 18, energy = 50, armor = 2, magic = 0, abilities = ['attack']},
		gear = 'peasant',
		skills = [],
	},
	centaur1 = {
		name = 'Centaur',
		code = 'centaur1',
		faction = 'monster',
		icon = load("res://files/images/enemies/stranger.png"),
		iconalt = load("res://files/images/enemies/stranger.png"),
		special = '',
		capture = true,
		capturerace = [['Centaur',100]],
		captureoriginspool = [{value = 'slave', weight = 1},{value = 'poor', weight = 1}],
		captureagepool = [{value = 'child', weight = 1},{value = 'teen', weight = 10}, {value = 'adult', weight = 30}],
		capturesex = ['any'],
		rewardpool = {gold = 10},
		rewardgold = [5,20],
		rewardexp = 20,
		stats = {health = 65, power = 6, speed = 18, energy = 50, armor = 2, magic = 0, abilities = ['attack']},
		gear = 'weakbandits',
		skills = [],
	},
	arachna1 = {
		name = 'Arachna',
		code = 'arachna1',
		faction = 'monster',
		icon = load("res://files/images/enemies/stranger.png"),
		iconalt = load("res://files/images/enemies/stranger.png"),
		special = '',
		capture = true,
		capturerace = [['Arachna',100]],
		captureoriginspool = [{value = 'slave', weight = 3},{value = 'poor', weight = 1}],
		captureagepool = [{value = 'child', weight = 1},{value = 'teen', weight = 1}, {value = 'adult', weight = 3}],
		capturesex = ['any'],
		rewardpool = {gold = 10},
		rewardgold = [5,20],
		rewardexp = 30,
		stats = {health = 65, power = 6, speed = 18, energy = 50, armor = 2, magic = 0, abilities = ['attack']},
		gear = 'forest',
		skills = [],
	},
	darkelf1 = {
		name = 'Dark Elf',
		code = 'darkelf1',
		faction = 'monster',
		icon = load("res://files/images/enemies/elfguard.png"),
		special = '',
		capture = true,
		capturerace = [['Dark Elf',100]],
		captureoriginspool = [{value = 'slave', weight = 1},{value = 'poor', weight = 3}],
		captureagepool = [{value = 'teen', weight = 1}, {value = 'adult', weight = 3}],
		capturesex = ['any'],
		rewardpool = {gold = 20, supply = 35},
		rewardgold = [1,5],
		rewardexp = 30,
		stats = {health = 65, power = 6, speed = 18, energy = 50, armor = 2, magic = 0, abilities = ['attack']},
		gear = 'elfs',
		skills = [],
	},
	#/ralphA
	#ralph4
	dryad2 = {
		name = 'Dryad',
		code = 'dryad2',
		faction = 'monster',
		icon = load("res://files/images/enemies/dryadm.png"),
		iconalt = load("res://files/images/enemies/dryadf.png"),
		special = '',
		capture = true,
		capturerace = [['Dryad',100]],
		captureoriginspool = [{value = 'commoner', weight = 1},{value = 'poor', weight = 1}],
		captureagepool = [{value = 'child', weight = 1},{value = 'teen', weight = 3}, {value = 'adult', weight = 4}],
		capturesex = ['any'],
		rewardpool = {natureessenceing = 35},
		rewardgold = [5,10],
		rewardexp = 30,
		stats = {health = 150, power = 6, speed = 24, energy = 60, armor = 4, magic = 0, abilities = ['attack']},
		gear = 'forest',
		skills = [],
	},
	nereidgroup = {
		name = 'Nereid',
		code = 'nereidgroup',
		faction = 'monster',
		icon = load("res://files/images/enemies/stranger.png"),
		iconalt = load("res://files/images/enemies/stranger.png"),
		special = '',
		capture = true,
		capturerace = [['Nereid',100]],
		captureoriginspool = [{value = 'commoner', weight = 1},{value = 'poor', weight = 1}],
		captureagepool = [{value = 'child', weight = 1},{value = 'teen', weight = 3}, {value = 'adult', weight = 6}],
		capturesex = ['any'],
		rewardpool = {},
		rewardgold = [5,20],
		rewardexp = 30,
		stats = {health = 200, power = 25, speed = 30, energy = 100, armor = 7, magic = 3, abilities = ['attack','stunattack']},
		gear = 'medbandits',
		skills = [],
	},
	#/ralph4
	monstergirl = {
		name = 'Monster ',
		code = 'monstergirl',
		faction = 'monster',
		icon = null,
		special = '',
		capture = true,
		capturerace = ['area'],
		captureoriginspool = [{value = 'rich', weight = 1},{value = 'commoner', weight = 3},{value = 'poor', weight = 2}],
		captureagepool = [{value = 'child', weight = 1},{value = 'teen', weight = 3}, {value = 'adult', weight = 6}], #ralph4
		capturesex = ['any'],
		rewardpool = {},
		rewardgold = [5,10],
		rewardexp = 25,
		stats = {health = 100, power = 15, speed = 22, energy = 50, armor = 2, magic = 1, abilities = ['attack']},
		gear = 'medbandits',
		skills = [],
	},
	bandit = {
		name = 'Bandit',
		code = 'bandit',
		faction = 'bandit',
		icon = load("res://files/images/enemies/banditm.png"),
		iconalt = load("res://files/images/enemies/banditf.png"),
		special = '',
		capture = true,
		capturerace = ['bandits'],
		captureoriginspool = [{value = 'commoner', weight = 1},{value = 'poor', weight = 5},{value = 'slave', weight = 2}],
		captureagepool = [{value = 'child', weight = 1},{value = 'teen', weight = 3}, {value = 'adult', weight = 5}],
		capturesex = ['any'],
		rewardpool = {gold = 35},
		rewardgold = [5,15],
		rewardexp = 20,
		stats = {health = 65, power = 4, speed = 14, energy = 50, armor = 2, magic = 0, abilities = ['attack']},
		gear = 'weakbandits',
		skills = [],
	},
	banditleader = {
		name = 'Bandit Leader',
		code = 'banditleader',
		faction = 'bandit',
		icon = load("res://files/images/enemies/banditleaderm.png"),
		iconalt = load("res://files/images/enemies/banditleaderf.png"),
		special = '',
		capture = true,
		capturerace = ['bandits'],
		captureoriginspool = [{value = 'rich', weight = 1},{value = 'commoner', weight = 3},{value = 'poor', weight = 2},{value = 'slave', weight = 1}],
		captureagepool = [{value = 'teen', weight = 1}, {value = 'adult', weight = 5}],
		capturesex = ['any'],
		rewardpool = {gold = 100},
		rewardgold = [30,50],
		rewardexp = 50,
		stats = {health = 90, power = 6, speed = 21, energy = 80, armor = 4, magic = 0, abilities = ['attack','stunattack']},
		gear = 'medbandits',
		skills = [],
	},
	marauder = {
		name = 'Marauder',
		code = 'marauder',
		faction = 'bandit',
		icon = load("res://files/images/enemies/banditleaderm.png"),
		iconalt = load("res://files/images/enemies/banditleaderf.png"),
		special = '',
		capture = true,
		capturerace = ['bandits'],
		captureoriginspool = [{value = 'rich', weight = 1},{value = 'commoner', weight = 3},{value = 'poor', weight = 4},{value = 'slave', weight = 1}],
		captureagepool = [{value = 'teen', weight = 1}, {value = 'adult', weight = 5}],
		capturesex = ['any'],
		rewardpool = {gold = 65},
		rewardgold = [25,40],
		rewardexp = 50,
		stats = {health = 100, power = 12, speed = 24, energy = 80, armor = 4, magic = 0, abilities = ['attack']},
		gear = 'medbandits',
		skills = [],
	},
	marauderleader = {
		name = 'Marauder Leader',
		code = 'marauder',
		faction = 'bandit',
		icon = load("res://files/images/enemies/banditleaderm.png"),
		iconalt = load("res://files/images/enemies/banditleaderf.png"),
		special = '',
		capture = true,
		capturerace = ['bandits'],
		captureoriginspool = [{value = 'rich', weight = 1},{value = 'commoner', weight = 3},{value = 'poor', weight = 4},{value = 'slave', weight = 1}],
		captureagepool = [{value = 'teen', weight = 1}, {value = 'adult', weight = 5}],
		capturesex = ['any'],
		rewardpool = {gold = 65},
		rewardgold = [25,40],
		rewardexp = 50,
		stats = {health = 120, power = 14, speed = 25, energy = 80, armor = 5, magic = 0, abilities = ['attack','stunattack']},
		gear = 'strongbandits',
		skills = [],
	},
	traveller = {
		name = 'Traveller',
		code = 'traveller',
		faction = 'stranger',
		icon = load("res://files/images/enemies/stranger.png"),
		special = '',
		capture = true,
		capturerace = ['area'],
		captureoriginspool = [{value = 'rich', weight = 1},{value = 'commoner', weight = 4},{value = 'poor', weight = 2}],
		captureagepool = [{value = 'child', weight = 1},{value = 'teen', weight = 3}, {value = 'adult', weight = 4}],
		capturesex = ['any'],
		rewardpool = {gold = 50, supply = 50},
		rewardgold = [5,15],
		rewardexp = 20,
		stats = {health = 50, power = 5, speed = 15, energy = 50, armor = 2, magic = 0, abilities = ['attack']},
		gear = 'peasant',
		skills = [],
	},
	slaver = {
		name = 'Slaver',
		code = 'slaver',
		faction = 'stranger',
		icon = load("res://files/images/enemies/slaverm.png"),
		iconalt = load("res://files/images/enemies/slaverf.png"),
		special = null,
		capture = true,
		capturerace = ['bandits'],
		captureoriginspool = [{value = 'slave', weight = 1},{value = 'commoner', weight = 3},{value = 'poor', weight = 4}],
		captureagepool = [{value = 'teen', weight = 1}, {value = 'adult', weight = 4}],
		capturesex = ['any'],
		rewardpool = {gold = 35, supply = 35},
		rewardgold = [5,15],
		rewardexp = 25,
		stats = {health = 70, power = 7, speed = 18, armor = 4, energy = 50, magic = 0, abilities = ['attack']},
		gear = 'medbandits',
		skills = [],
	},
	wimbornpatrol = {
		name = 'Wimborn Defender',
		code = 'wimbornpatrol',
		faction = 'stranger',
		icon = load("res://files/images/enemies/humanguard.png"),
		special = null,
		capture = true,
		capturerace = ['wimborn'],
		captureoriginspool = [{value = 'rich', weight = 1},{value = 'commoner', weight = 3},{value = 'poor', weight = 3}],
		captureagepool = [{value = 'teen', weight = 1}, {value = 'adult', weight = 4}],
		capturesex = ['any'],
		rewardpool = {gold = 20, supply = 35},
		rewardgold = [1,5],
		rewardexp = 25,
		stats = {health = 100, power = 25, speed = 35, energy = 50, armor = 5, magic = 2, abilities = ['attack']},
		gear = 'guard',
		skills = [],
	},
	frostfordpatrol = {
		name = 'Frostford Defender',
		code = 'frostfordpatrol',
		faction = 'stranger',
		icon = load("res://files/images/enemies/wolfguard.png"),
		special = null,
		capture = true,
		capturerace = ['frostford'],
		captureoriginspool = [{value = 'rich', weight = 1},{value = 'commoner', weight = 3},{value = 'poor', weight = 3}],
		captureagepool = [{value = 'teen', weight = 1}, {value = 'adult', weight = 4}],
		capturesex = ['any'],
		rewardpool = {gold = 20, supply = 35},
		rewardgold = [1,5],
		rewardexp = 25,
		stats = {health = 100, power = 23, speed = 33, energy = 50, armor = 5, magic = 2, abilities = ['attack']},
		gear = 'guard',
		skills = [],
	},
	gornpatrol = {
		name = 'Gorn Defender',
		code = 'gornpatrol',
		faction = 'stranger',
		icon = load("res://files/images/enemies/orcguard.png"),
		special = null,
		capture = true,
		capturerace = ['gorn'],
		captureoriginspool = [{value = 'rich', weight = 1},{value = 'commoner', weight = 3},{value = 'poor', weight = 3}],
		captureagepool = [{value = 'teen', weight = 1}, {value = 'adult', weight = 4}],
		capturesex = ['any'],
		rewardpool = {gold = 20, supply = 35},
		rewardgold = [1,5],
		rewardexp = 25,
		stats = {health = 120, power = 30, speed = 34, energy = 50, armor = 4, magic = 2, abilities = ['attack']},
		gear = 'guard',
		skills = [],
	},
	amberguardpatrol = {
		name = 'Amberguard Defender',
		code = 'amberpatrol',
		faction = 'stranger',
		icon = load("res://files/images/enemies/elfguard.png"),
		special = null,
		capture = true,
		capturerace = ['amberguard'],
		captureoriginspool = [{value = 'rich', weight = 1},{value = 'commoner', weight = 3},{value = 'poor', weight = 3}],
		captureagepool = [{value = 'teen', weight = 1}, {value = 'adult', weight = 4}],
		capturesex = ['any'],
		rewardpool = {gold = 20, supply = 35},
		rewardgold = [1,5],
		rewardexp = 25,
		stats = {health = 100, power = 16, speed = 35, energy = 50, armor = 4, magic = 2, abilities = ['attack']},
		gear = 'guard',
		skills = [],
	},



	ivran = {
		name = 'An Elf Leader',
		code = 'ivran',
		faction = 'elf',
		icon = load("res://files/aric_expansion_images/characters/ivranenemyicon.png"),
		special = null,
		capture = true,
		capturerace = [['Tribal Elf',100]],
		captureoriginspool = [{value = 'noble', weight = 100}],
		captureagepool = [{value = 'adult', weight = 100}],
		capturesex = ['any'],
		rewardpool = {gold = 20},
		rewardgold = [5,10],
		rewardexp = 50,
		stats = {health = 100, power = 24, speed = 25, energy = 50, armor = 4, magic = 2, abilities = ['attack']},
		gear = 'weakbandits',
		skills = [],
	},
	ayneris = {
		name = 'An Elf Leader',
		code = 'ayneris',
		faction = 'elf',
		icon = load("res://files/images/ayneris/aynerisportrait.png"),
		special = null,
		capture = true,
		capturerace = [['Elf',100]],
		captureoriginspool = [{value ='noble', weight = 100}],
		captureagepool = [{value = 'teen', weight = 100}],
		capturesex = [['female',100]],
		rewardpool = {gold = 20},
		rewardgold = [5,10],
		rewardexp = 40,
		stats = {health = 110, power = 26, speed = 25, energy = 50, armor = 5, magic = 3, abilities = ['attack', 'aimedstrike'], passives = ['doubleattack50']},
		gear = 'weakbandits',
		skills = [],
	},
	#undercity
	mutant = {
		name = 'Crazed mutant',
		code = 'mutant',
		faction = 'animal',
		icon = load("res://files/images/enemies/mutant.png"),
		special = null,
		capture = null,
		level = 15,
		rewardpool = {taintedessenceing = 40, armortentacle = 5, clothtentacle = 5},
		rewardgold = 0,
		rewardexp = 50,
		stats = {health = 150, power = 30, speed = 22, energy = 50, armor = 2, magic = 2, abilities = ['attack', 'acidspit']},
		skills = [],
	},
	troglodyte = {
		name = 'Troglodyte',
		code = 'troglodyte',
		faction = 'animal',
		level = 12,
		icon = load("res://files/images/enemies/troglodyte.png"),
		special = null,
		capture = null,
		rewardpool = {taintedessenceing = 40, accslavecollar = 3},
		rewardgold = 0,
		rewardexp = 50,
		stats = {health = 90, power = 25, speed = 18, energy = 50, armor = 2, magic = 2, abilities = ['attack']},
		gear = 'weakbandits',
		skills = [],
	},
	gembeetle = {
		name = 'Gem Beetle',
		code = 'gembeetle',
		faction = 'animal',
		icon = load("res://files/images/enemies/gembettle.png"),
		special = null,
		capture = null,
		level = 6,
		rewardpool = {gem = 50},
		rewardgold = 0,
		rewardexp = 10,
		stats = {health = 75, power = 30, speed = 20, energy = 50, armor = 15, magic = 2, abilities = ['attack']},
		skills = [],
	},
	bossgolem = {
		name = 'Animated Golem',
		code = 'bossgolem',
		faction = 'boss',
		icon = load("res://files/images/enemies/golem.png"),
		special = null,
		capture = null,
		rewardpool = {gem = 50},
		rewardgold = 0,
		rewardexp = 150,
		stats = {health = 500, power = 60, speed = 25, energy = 50, armor = 13, magic = 2, abilities = ['attack','aoeattack']},
		skills = [],
	},
	bosswyvern = {
		name = 'Cave Wyvern',
		code = 'bosswyvern',
		faction = 'boss',
		icon = load("res://files/images/enemies/wyvern.png"),
		special = null,
		capture = null,
		rewardpool = {gem = 50},
		rewardgold = 0,
		rewardexp = 100,
		stats = {health = 450, power = 60, speed = 30, energy = 50, armor = 10, magic = 2, abilities = ['attack','aoeattack']},
		skills = [],
	},

	dragonwhelp = {
		name = 'Dragon Whelp',
		code = 'dragonwhelp',
		faction = 'animal',
		icon = load("res://files/images/enemies/dragonwhelp.png"),
		special = null,
		capture = null,
		rewardpool = {gold = 50},
		rewardgold = [15,75],
		level = 20,
		rewardexp = 75,
		stats = {health = 200, power = 100, speed = 40, energy = 50, armor = 5, magic = 10, abilities = ['attack']},
		skills = [],
	},
	hardbeast = {
		name = 'Hardened Beast',
		code = 'hardbeast',
		faction = 'animal',
		icon = load("res://files/images/enemies/hardbeast.png"),
		special = null,
		capture = null,
		rewardpool = {armorcarapace = 3, armorplate = 3},
		level = 23,
		rewardgold = 0,
		rewardexp = 60,
		stats = {health = 300, power = 80, speed = 29, energy = 50, armor = 25, magic = 10, abilities = ['attack','heavystike']},
		skills = [],
	},
	possessed = {
		name = 'Possessed',
		code = 'possessed',
		faction = 'bandit',
		icon = load("res://files/images/enemies/possessed.png"),
		special = null,
		capture = null,
		level = 24,
		rewardpool = {gold = 50},
		rewardgold = [5,50],
		rewardexp = 45,
		stats = {health = 200, power = 65, speed = 25, energy = 50, armor = 5, magic = 10, abilities = ['attack']},
		skills = [],
	},
	cultist = {
		name = 'Cultist',
		code = 'cultist',
		faction = 'bandit',
		icon = load("res://files/images/enemies/cultist.png"),
		special = null,
		capture = null,
		level = 25,
		rewardpool = {gold = 35},
		rewardgold = [5,50],
		rewardexp = 50,
		stats = {health = 250, power = 50, speed = 30, energy = 50, armor = 15, magic = 10, abilities = ['attack', 'alwayshitattack']},
		skills = [],
	},
	giantcrab = {
		name = 'Giant Crab',
		code = 'giantcrab',
		faction = 'animal',
		icon = load("res://files/images/enemies/crab.png"),
		special = null,
		capture = null,
		level = 25,
		rewardpool = {},
		rewardgold = 0,
		rewardexp = 100,
		stats = {health = 300, power = 90, speed = 30, energy = 50, armor = 40, magic = 10, abilities = ['attack','aoeattack']},
		skills = [],
	},
	shadow = {
		name = 'Shadow',
		code = 'shadow',
		faction = '',
		icon = load("res://files/images/enemies/shadow.png"),
		special = null,
		capture = null,
		level = 28,
		rewardpool = {},
		rewardgold = 0,
		rewardexp = 80,
		stats = {health = 150, power = 120, speed = 40, energy = 50, armor = 0, magic = 10, abilities = ['attack','debilitate','leechingstrike']},
		skills = [],
	},

	bossdragon = {
		name = 'Corrupted Dragon',
		code = 'bossdragon',
		faction = 'boss',
		icon = load("res://files/images/enemies/dragonboss.png"),
		special = null,
		capture = null,
		rewardpool = {},
		rewardgold = 0,
		rewardexp = 200,
		stats = {health = 750, power = 150, speed = 40, energy = 50, armor = 25, magic = 10, abilities = ['attack','dragonfirebreath']},
		skills = [],
	},


	cultboss = {
		name = 'Cultist Leader',
		code = 'cultboss',
		faction = 'boss',
		icon = load("res://files/images/enemies/cultistboss.png"),
		special = null,
		capture = null,
		rewardpool = {},
		rewardgold = 0,
		rewardexp = 350,
		stats = {health = 500, power = 120, speed = 45, energy = 50, armor = 10, magic = 10, abilities = ['attack'], passives = ['cultleaderpassive']},
		skills = [],
	},
	finalboss = {
		name = '??',
		code = 'finalboss',
		faction = 'boss',
		icon = load("res://files/images/enemies/darkboss.png"),
		special = null,
		capture = null,
		rewardpool = {},
		rewardgold = 0,
		rewardexp = 500,
		stats = {health = 1000, power = 200, speed = 40, energy = 50, armor = 20, magic = 8, abilities = ['attack', 'darknessattack']},
		skills = [],
	},
}

###---Added by Expansion---### ElPresidente Items
var enemyequips = {
	weakbandits = {
		armor = [['nothing', 10], ['armorleather',10], ['armorchain', 1], ['armorleather+', 1],['armorpadded', 5]],
		weapon = [['weapondagger',10], ['weaponbasicstaff',5], ['weaponserrateddagger', 2], ['weaponsword', 2], ['weapondagger+', 2], ['weaponbasicstaff+',2]],
		abilities = [],
	},
	medbandits = {
		armor = [['armorleather+',3], ['armorchain', 3], ['armorchain+', 1], ['armorninja', 0.5], ['armorrogue', 0.1],['armorpadded', 5],['armorpadded+', 1],['armorhalfplate',1]],
		weapon = [['weaponsword', 4], ['weaponsword+', 1], ['weaponbasicstaff+',2], ['weaponserrateddagger', 4], ['weapondagger+', 2], ['weaponserrateddagger+', 1], ['weaponhammer', 0.1]],
		accessory = [['accamuletruby', 1], ['nothing',10]],
		abilities = [],
	},
	strongbandits = {
		armor = [['armorchain', 8], ['armorchain+', 2], ['armorninja', 1], ['armorninja+', 0.1], ['armorrogue', 0.2], ['armorplate', 0.5], ['armorplate+', 0.1],['armorhalfplate',1]],
		weapon = [['weaponsword', 4], ['weaponsword+', 1], ['weaponbasicstaff+',2], ['weaponserrateddagger', 4], ['weaponserrateddagger+', 1], ['weaponclaymore', 2], ['weaponclaymore+', 0.3], ['weaponhammer', 1], ['weaponhammer+', 0.2]],
		accessory = [['accamuletruby', 1], ['accamuletemerald',1], ['accamuletruby+', 0.3], ['accamuletemerald+',0.3]],
		abilities = [],
	},
	elfs = {
		armor = [['armorchain', 3], ['armorchain+', 1], ['armorelvenchain', 10], ['armorelvenchain+', 2],['armorelvenhalfplate', 0.25], ['armorelvenhalfplate+', 0.1]],
		weapon = [['weaponelvensword', 4], ['weaponelvensword+', 1], ['weapondagger+', 2], ['weaponserrateddagger+', 2], ['weaponancientsword', 4], ['weaponancientsword+',0.5]],
		accessory = [['accamuletemerald', 1], ['accamuletemerald+', 1],['accelvenboots', 1],['nothing',10]],
		abilities = [],
	},
	peasant = {
		armor = [['nothing', 25],['armorleather',10], ['armorleather+', 1],['armorpadded', 5]],
		weapon = [['nothing', 7],['weapondagger',10], ['weapondagger+', 2]],
		abilities = [],
	},
	forest = {
		armor = [['armorleather',10], ['armorleather+', 3]],
		weapon = [['nothing', 5],['weapondagger+', 3],['weaponnaturestaff', 2],['weaponnaturestaff+', 0.5]],
		accessory = [['accamuletemerald', 1], ['accamuletemerald+', 0.2],['nothing',3]],
		abilities = [],
	},
	marsh = {
		armor = [['armorleather',10], ['armorleather+', 3]],
		weapon = [['nothing', 5], ['weaponsword+', 3], ['weaponserrateddagger+', 3], ['weaponnaturestaff', 2], ['weaponnaturestaff+', 0.5]],
		accessory = [['accamuletemerald', 1], ['accamuletemerald+', 0.2],['nothing',3]],
		abilities = [],
	},
	guard = {
		armor = [ ['armorchain', 10], ['armorchain+', 3], ['armorplate',1], ['armorhalfplate',1], ['armorplate+', 0.3]],
		weapon = [['weaponsword', 5], ['weaponsword+', 1],  ['weaponhammer', 1], ['weaponhammer+', 0.2], ['weaponceremonialsword', 1], ['weapongreatsword', 1], ['weapongreatsword+', 0.25]],
		accessory = [['accgoldring', 1], ['nothing',10]],
		abilities = [],
	},
}

