###---Added By Expansion---### Expanded Areas Quest Text (Bubblepot)
#GreatTreeNest
var spinebossenc= "The wind suddenly picks up and with a mighty rush of air a gigantic bird lands before you, shaking the nest with its weight.\n\n It rears up and spreads its wings, displaying a wingspan big enough to cover a small neighbourhood. It's raptor gaze rests on you with something incredibly like contempt.\n\n You ready your weapons just as it unleashes a deafening screech and sends gales of wind rushing toward you.  "
var spinebosswin= "The great bird stumbles backwards, dazed. It shakes off the daze just as you're rushing toward it and screeches once more. With three flaps of its immense wings it blows you off the tree entirely."
var spinebosswin2= "The great bird falls to the ground with a final weak screech and dies. It appears to have several treasures in its next. Most are too big for you to carry with you."

#Desert
var prairiebossenc
var prairiebosswin

#Sea
var seabossenc= "At the centre of the cavern a giant serpent lays curled at the very bottom of a whirlpool. Mysteriously, the rough current does not displace its position even slightly. The water here glows with an otherwordly quality. \n\n The great serpent opens a single glowing green eye. The eye alone looks big enough that if it were to pop from its socket it would crush you. The serpent uncoils revealing its scaly bulk fully. Even lying on the floor it was big enough to be mistaken for a small mountain within the cavern. Now that it has reared up its head brushes the roof of the cavern and its body curls around the perimetre, sealing the entrance. \n\n It's roar of challenge vibrates the cavern and everything in it. "
var seabosswin= "The serpent rears back hissing furiously. Instinct warns you and you erect a barrier just as it opens its maw and shoots a beam of raw magic at you. \n\n Your barrier is a pebble in a rushing river, resistant only due to its condensed nature. Even so it begins to crack and a deep fear grips you that this creature may know how to focus its magic and expose your barrier for the flimsy thing it really is.\n\n You are blasted out of the cavern."
var seabosswin2= "The serpents body floats gently to the floor, a stark contrast with the violence that just took place. You notice that the cavern is littered with many sunken treasures."

#Hellscape
var hellenc= "A great horned Demon stands before you grinning so wide that all its pointed teeth are on display. It is almost no different from demons as you know them... Except you can feel the weight of its magical presence and know that no demon could be this powerful. Its body rolls with muscle. An aura of red burns hungrily around it, and its yellow eyes seem to be slowly lighting up with some kind of magical fire.\n\n  [color=red]Welcome to my playground, foolish mortal. Tell me? How do you wish to die?[/color]\n\n Before you can respond it rushes at you."
var hellbosswin= "[color=red]How entertaining![/color] the Demon laughs as it stands up. \n\n Your next swing is blocked effortlessly and your follow up spell is swatted aside. The Demon knocks you away with a kick and suddenly explodes with new power. \n\n [color=red]You proved interesting mortal. I'm almost tempted to have offspring with you just to see how they would turn out.[/color] The Demon licks its lips. [color=red]But first, let's see if this is your full potential hmmm?[/color]\n\n It holds out one hand, palm up, with two fingers pointed in your direction. You tense, preparing to counter whatever the spell may be. \n\n The Demon flicks its fingers upward. [color=red]Become stronger! Become more entertaining! Then you may return to amuse me.[/color] \n\n A pillar of flame erupts around you before you even get to cast a spell. It feels like you're burning to ash. You scream.\n\n ...It appears you are back in the marsh, lying in a pool of muddy water. Ew." 

#Colliseum
var skybossenc= "You step into the arena and find a Seraph standing before you, but it is like no Seraph you've ever seen. It glows with power.\n\n [color=gold]You tresspass mortal.[/color]\n\n The faint twitch of the sword in its hand gives you pause. \n\n [color=gold]Leave.[/color]\n\n There is no room for reason or argument. It waits patiently for you to leave.\n\n After several seconds of silence, the Seraph raises its perfect eyebrows.[color=gold]You refuse? Then the time for words is past.[/color] Its free hand glows with golden light as it points its sword at you. [color=gold]You will learn by experience what you refuse to learn with instruction.[/color]"
var skybosswin= "The battle is still going strong, when all of a sudden the lone Seraph seems to come to a decision. Your next attacks are all dodged, blocked or directly nullified, each response seemingly based on a whim. \n\n[color=gold]Further escalation will kill you. Your stubborness has persisted long enough.[/color] \n\n It leaps into the air with a single flap, aiming its palm at the arena. [color=gold]Begone.[/color]\n\n A golden light flares and the arena dissolves into waves and waves of raw magic, sweeping you up in its force. Overwhelmed, you begin to drown...\n\n You wake up at Storm Crown. It appears that you have been kicked out of... whatever that place was."

###---Expansion End---###
